// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default [
 {
  "id": 17676,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      }
     ]
    ],
    "paddingPositions": [
     35,
     33,
     9,
     25,
     15
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 2,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 8232,
  "payoutMultiplier": 100,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ]
    ],
    "paddingPositions": [
     16,
     0,
     35,
     43,
     36
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 100,
    "wins": [
     {
      "symbol": "H5",
      "kind": 3,
      "win": 100,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 4
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 4,
       "multiplier": 1,
       "winWithoutMult": 100,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 100,
    "winLevel": 3
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 100
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 100
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 1.0,
  "freeGameWins": 0.0
 },
 {
  "id": 21553,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     63,
     33,
     58,
     54,
     55
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     1
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 1
       },
       {
        "reel": 2,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 1,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 35525,
  "payoutMultiplier": 440,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ]
    ],
    "paddingPositions": [
     58,
     36,
     44,
     63,
     54
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 440,
    "wins": [
     {
      "symbol": "H3",
      "kind": 3,
      "win": 400,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 2,
       "multiplier": 1,
       "winWithoutMult": 400,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "L3",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 13,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 440,
    "winLevel": 4
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 440
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 440
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 4.4,
  "freeGameWins": 0.0
 },
 {
  "id": 2630,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      }
     ]
    ],
    "paddingPositions": [
     34,
     43,
     52,
     38,
     50
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 9,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 3956,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     23,
     54,
     26,
     11,
     0
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 10,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 29239,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     49,
     45,
     27,
     8,
     18
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 3,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 5113,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "H2"
      }
     ]
    ],
    "paddingPositions": [
     28,
     36,
     50,
     0,
     6
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     1
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 11,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 19956,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      }
     ]
    ],
    "paddingPositions": [
     14,
     53,
     17,
     29,
     2
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L3",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 11,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 31716,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      }
     ]
    ],
    "paddingPositions": [
     27,
     7,
     44,
     26,
     59
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 6,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 3146,
  "payoutMultiplier": 400,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      }
     ]
    ],
    "paddingPositions": [
     53,
     32,
     25,
     23,
     51
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 400,
    "wins": [
     {
      "symbol": "L3",
      "kind": 5,
      "win": 200,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 1
       },
       {
        "reel": 2,
        "row": 1
       },
       {
        "reel": 3,
        "row": 1
       },
       {
        "reel": 4,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 1,
       "multiplier": 1,
       "winWithoutMult": 200,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "L2",
      "kind": 5,
      "win": 200,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       },
       {
        "reel": 3,
        "row": 3
       },
       {
        "reel": 4,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 6,
       "multiplier": 1,
       "winWithoutMult": 200,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 400,
    "winLevel": 4
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 400
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 400
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 4.0,
  "freeGameWins": 0.0
 },
 {
  "id": 27682,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      }
     ]
    ],
    "paddingPositions": [
     45,
     48,
     25,
     10,
     42
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     1,
     2,
     3
    ]
   },
   {
    "index": 1,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 2,
    "type": "freeSpinTrigger",
    "totalFs": 10,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 3,
      "row": 1
     }
    ]
   },
   {
    "index": 3,
    "type": "bonusTier",
    "tier": "midnight_passage",
    "seedFrames": 0
   },
   {
    "index": 4,
    "type": "updateFreeSpin",
    "amount": 0,
    "total": 10
   },
   {
    "index": 5,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     28,
     18,
     10,
     25,
     50
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 6,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 7,
    "type": "updateFreeSpin",
    "amount": 1,
    "total": 10
   },
   {
    "index": 8,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     59,
     18,
     43,
     57,
     30
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 9,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 10,
    "type": "updateFreeSpin",
    "amount": 2,
    "total": 10
   },
   {
    "index": 11,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      }
     ]
    ],
    "paddingPositions": [
     23,
     24,
     2,
     14,
     49
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     1,
     2
    ]
   },
   {
    "index": 12,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 13,
    "type": "updateFreeSpin",
    "amount": 3,
    "total": 10
   },
   {
    "index": 14,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     53,
     53,
     11,
     10,
     24
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     1
    ]
   },
   {
    "index": 15,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 16,
    "type": "updateFreeSpin",
    "amount": 4,
    "total": 10
   },
   {
    "index": 17,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      }
     ]
    ],
    "paddingPositions": [
     39,
     28,
     31,
     37,
     48
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 18,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 19,
    "type": "updateFreeSpin",
    "amount": 5,
    "total": 10
   },
   {
    "index": 20,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ]
    ],
    "paddingPositions": [
     32,
     39,
     37,
     45,
     13
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 21,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 22,
    "type": "updateFreeSpin",
    "amount": 6,
    "total": 10
   },
   {
    "index": 23,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      }
     ]
    ],
    "paddingPositions": [
     56,
     16,
     32,
     59,
     48
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 24,
    "type": "multiplierWheel",
    "previous": 1,
    "value": 1,
    "eligibleValues": [
     1,
     2,
     3,
     4,
     5,
     6,
     8,
     10,
     15,
     20,
     25,
     30,
     40,
     50,
     75,
     100
    ]
   },
   {
    "index": 25,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L3",
      "kind": 3,
      "win": 40,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 5,
       "multiplier": 1,
       "winWithoutMult": 40,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 26,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 27,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 28,
    "type": "updateFreeSpin",
    "amount": 7,
    "total": 10
   },
   {
    "index": 29,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ]
    ],
    "paddingPositions": [
     42,
     38,
     41,
     56,
     7
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 30,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 31,
    "type": "updateFreeSpin",
    "amount": 8,
    "total": 10
   },
   {
    "index": 32,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     19,
     14,
     26,
     26,
     56
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 33,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 34,
    "type": "updateFreeSpin",
    "amount": 9,
    "total": 10
   },
   {
    "index": 35,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      }
     ]
    ],
    "paddingPositions": [
     54,
     3,
     18,
     63,
     55
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 36,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 37,
    "type": "freeSpinEnd",
    "amount": 40,
    "winLevel": 1
   },
   {
    "index": 38,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "freegame_weak",
  "baseGameWins": 0.0,
  "freeGameWins": 0.4
 }
];
