// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L4"
    },
    {
     "name": "L1"
    },
    {
     "name": "L2"
    },
    {
     "name": "H4"
    },
    {
     "name": "L2"
    },
    {
     "name": "L4"
    }
   ],
   [
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L2"
    },
    {
     "name": "W",
     "wild": true
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "H2"
    },
    {
     "name": "L4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "L2"
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    }
   ]
  ],
  "paddingPositions": [
   35,
   33,
   9,
   25,
   15
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   0
  ]
 },
 "winInfo": {
  "index": 1,
  "type": "winInfo",
  "totalWin": 40,
  "wins": [
   {
    "symbol": "L2",
    "kind": 3,
    "win": 40,
    "positions": [
     {
      "reel": 0,
      "row": 2
     },
     {
      "reel": 1,
      "row": 2
     },
     {
      "reel": 2,
      "row": 2
     }
    ],
    "meta": {
     "lineIndex": 2,
     "multiplier": 1,
     "winWithoutMult": 40,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 2,
  "type": "setWin",
  "amount": 40,
  "winLevel": 2
 },
 "setTotalWin": {
  "index": 3,
  "type": "setTotalWin",
  "amount": 40
 },
 "finalWin": {
  "index": 4,
  "type": "finalWin",
  "amount": 40
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 4
   },
   {
    "reel": 1,
    "row": 3
   },
   {
    "reel": 3,
    "row": 1
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "midnight_passage",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 24,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 1,
  "eligibleValues": [
   1,
   2,
   3,
   4,
   5,
   6,
   8,
   10,
   15,
   20,
   25,
   30,
   40,
   50,
   75,
   100
  ]
 },
 "freeSpinEnd": {
  "index": 37,
  "type": "freeSpinEnd",
  "amount": 40,
  "winLevel": 1
 }
};
