// Generated by design/sync_story_books.py from books_bonus_hits.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L4"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "L2"
    },
    {
     "name": "L4"
    },
    {
     "name": "H3"
    }
   ],
   [
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H4"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "L1"
    },
    {
     "name": "L2"
    },
    {
     "name": "H5"
    },
    {
     "name": "L4"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "H2"
    },
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H3"
    }
   ]
  ],
  "paddingPositions": [
   48,
   16,
   31,
   25,
   15
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   1,
   2,
   3
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 1
   },
   {
    "reel": 1,
    "row": 1
   },
   {
    "reel": 3,
    "row": 3
   },
   {
    "reel": 4,
    "row": 4
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "phantom_express",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 6,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 5,
  "eligibleValues": [
   5,
   10,
   15,
   20,
   25,
   30,
   35,
   40,
   45,
   50,
   55,
   60,
   65,
   70,
   75,
   80,
   85,
   90,
   95,
   100
  ]
 },
 "winInfo": {
  "index": 7,
  "type": "winInfo",
  "totalWin": 200,
  "wins": [
   {
    "symbol": "L3",
    "kind": 3,
    "win": 200,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 3
     }
    ],
    "meta": {
     "lineIndex": 3,
     "multiplier": 5,
     "winWithoutMult": 40,
     "globalMult": 5,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 8,
  "type": "setWin",
  "amount": 200,
  "winLevel": 4
 },
 "freeSpinRetrigger": {
  "index": 16,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 2,
    "row": 1
   },
   {
    "reel": 4,
    "row": 1
   }
  ]
 },
 "freeSpinEnd": {
  "index": 62,
  "type": "freeSpinEnd",
  "amount": 250200,
  "winLevel": 9
 },
 "finalWin": {
  "index": 63,
  "type": "finalWin",
  "amount": 250200
 }
};
