// Generated by design/sync_story_books.py from books_bonus.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "H1"
    },
    {
     "name": "H4"
    },
    {
     "name": "H5"
    },
    {
     "name": "H4"
    },
    {
     "name": "L1"
    },
    {
     "name": "H5"
    }
   ],
   [
    {
     "name": "H4"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "H3"
    },
    {
     "name": "H4"
    },
    {
     "name": "L4"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "H3"
    },
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "L4"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H5"
    },
    {
     "name": "H3"
    },
    {
     "name": "L3"
    },
    {
     "name": "L4"
    }
   ],
   [
    {
     "name": "L2"
    },
    {
     "name": "L1"
    },
    {
     "name": "L4"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    },
    {
     "name": "H5"
    }
   ]
  ],
  "paddingPositions": [
   17,
   9,
   19,
   36,
   35
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   1
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 1,
    "row": 1
   },
   {
    "reel": 3,
    "row": 1
   },
   {
    "reel": 4,
    "row": 3
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "midnight_passage",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 6,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 10,
  "eligibleValues": [
   2,
   4,
   6,
   8,
   10,
   12,
   16,
   20,
   30,
   40,
   50,
   60,
   80,
   100,
   150,
   200
  ]
 },
 "winInfo": {
  "index": 7,
  "type": "winInfo",
  "totalWin": 200,
  "wins": [
   {
    "symbol": "L3",
    "kind": 3,
    "win": 200,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 2
     },
     {
      "reel": 2,
      "row": 2
     }
    ],
    "meta": {
     "lineIndex": 11,
     "multiplier": 10,
     "winWithoutMult": 20,
     "globalMult": 10,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 8,
  "type": "setWin",
  "amount": 200,
  "winLevel": 4
 },
 "freeSpinRetrigger": {
  "index": 46,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 3,
    "row": 2
   },
   {
    "reel": 4,
    "row": 4
   }
  ]
 },
 "freeSpinEnd": {
  "index": 59,
  "type": "freeSpinEnd",
  "amount": 22000,
  "winLevel": 7
 },
 "finalWin": {
  "index": 60,
  "type": "finalWin",
  "amount": 22000
 }
};
