// Generated by design/sync_story_books.py from books_bonus.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L2"
    },
    {
     "name": "L4"
    },
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    },
    {
     "name": "H2"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L2"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "H2"
    }
   ],
   [
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    }
   ]
  ],
  "paddingPositions": [
   7,
   14,
   4,
   25,
   16
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   1
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 1,
    "row": 3
   },
   {
    "reel": 3,
    "row": 3
   },
   {
    "reel": 4,
    "row": 3
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "midnight_passage",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 12,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 3,
  "eligibleValues": [
   1,
   2,
   3,
   4,
   5,
   6,
   8,
   10,
   15,
   20,
   25,
   30,
   40,
   50,
   75,
   100
  ]
 },
 "winInfo": {
  "index": 13,
  "type": "winInfo",
  "totalWin": 6000,
  "wins": [
   {
    "symbol": "H3",
    "kind": 4,
    "win": 6000,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 4
     },
     {
      "reel": 3,
      "row": 3
     }
    ],
    "meta": {
     "lineIndex": 14,
     "multiplier": 3,
     "winWithoutMult": 2000,
     "globalMult": 3,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 14,
  "type": "setWin",
  "amount": 6000,
  "winLevel": 8
 },
 "freeSpinEnd": {
  "index": 43,
  "type": "freeSpinEnd",
  "amount": 7120,
  "winLevel": 6
 },
 "finalWin": {
  "index": 44,
  "type": "finalWin",
  "amount": 7120
 },
 "freeSpinRetrigger": {
  "index": 10,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 3,
    "row": 4
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 }
};
