"""Pull a handful of real books out of the math output for the replay harness.

The game cannot be started locally without an RGS, which left every presentation
change - win highlight, board expansion, scatter alarm - unverifiable except by
uploading. make_replay_harness.mjs fixes that by mocking the replay endpoint, and
this produces the books it serves.

Rounds are chosen to cover the cases that keep going wrong rather than at random:
wins that run onto the later reels, a feature round, and a wincap.

    python design/extract_books.py

Writes src/stories/data/{base,bonus}_books.ts.
"""

import io
import json
import os
import sys

import zstandard as zstd

APP_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLISH = os.path.join(
    APP_ROOT, '..', '..', '..', 'math-sdk', 'games', 'TripleWitching', 'library', 'publish_files'
)
OUT_DIR = os.path.join(APP_ROOT, 'src', 'stories', 'data')


def read_books(path, limit=60000):
    with open(path, 'rb') as handle:
        reader = zstd.ZstdDecompressor().stream_reader(handle)
        for i, line in enumerate(io.TextIOWrapper(reader, encoding='utf-8')):
            if i >= limit:
                return
            line = line.strip()
            if line:
                yield json.loads(line)


def win_reels(book):
    """Widest reel span of any single win in the book."""
    widest = 0
    for event in book['events']:
        if event['type'] != 'winInfo':
            continue
        for win in event['wins']:
            widest = max(widest, win['kind'])
    return widest


def pick(path, wanted):
    """wanted: list of (label, predicate). First match for each, in file order."""
    found = {}
    for book in read_books(path):
        for label, predicate in wanted:
            if label in found:
                continue
            if predicate(book):
                found[label] = book
        if len(found) == len(wanted):
            break
    return found


def write(name, books):
    os.makedirs(OUT_DIR, exist_ok=True)
    header = (
        '// GENERATED by design/extract_books.py - real rounds from the math output,\n'
        '// used by design/make_replay_harness.mjs to run the game without an RGS.\n'
    )
    payload = [
        {'id': b['id'], 'payoutMultiplier': b['payoutMultiplier'], 'events': b['events']}
        for b in books
    ]
    out = os.path.join(OUT_DIR, f'{name}_books.ts')
    with open(out, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(header + 'export default ' + json.dumps(payload) + ';\n')
    kb = os.path.getsize(out) / 1024
    print(f'  {name}_books.ts  {len(payload)} books  {kb:.0f} KB')
    for b in payload:
        kinds = sorted(
            {w['kind'] for e in b['events'] if e['type'] == 'winInfo' for w in e['wins']}
        )
        types = {e['type'] for e in b['events']}
        print(
            f"    id {b['id']:<7} x{b['payoutMultiplier'] / 100:<9.2f} "
            f"kinds={kinds} feature={'boardExpand' in types}"
        )


if __name__ == '__main__':
    base_path = os.path.join(PUBLISH, 'books_base.jsonl.zst')
    bonus_path = os.path.join(PUBLISH, 'books_bonus.jsonl.zst')
    if not os.path.exists(base_path):
        print(f'no books at {base_path} - run the math pipeline first', file=sys.stderr)
        sys.exit(1)

    base = pick(
        base_path,
        [
            # the case that keeps failing: a win that runs onto the later reels
            ('five', lambda b: win_reels(b) == 5),
            ('four', lambda b: win_reels(b) == 4),
            ('three', lambda b: win_reels(b) == 3),
            ('feature', lambda b: any(e['type'] == 'boardExpand' for e in b['events'])),
        ],
    )
    bonus = pick(
        bonus_path,
        [
            ('feature', lambda b: any(e['type'] == 'boardExpand' for e in b['events'])),
            ('big', lambda b: b['payoutMultiplier'] > 50000),
        ],
    )

    print('extracted:')
    write('base', [base[k] for k in ('five', 'four', 'three', 'feature') if k in base])
    write('bonus', [bonus[k] for k in ('feature', 'big') if k in bonus])
