// Local replay test harness.
//
// Replay mode can only be exercised against an RGS that serves
// /bet/replay/{game}/{version}/{mode}/{event}, and Stake Engine only serves that
// for real historical bets. That left the entire replay presentation — playback,
// the replay-again button, the state left behind between runs — untestable
// locally, which is exactly the part that kept shipping broken.
//
// This builds a COPY of build/ with a service worker that answers the replay
// request from books already in the repo. The shipped build is never touched:
// the mock lives only in build-replaytest/, which is gitignored.
//
// A service worker rather than a stub server because rgs-fetcher hardcodes
// `https://${rgsUrl}` — a local stub would need a certificate the browser
// trusts, whereas a worker can answer a cross-origin request with a synthetic
// response and needs nothing but localhost.
//
// Usage:
//   pnpm --dir apps/TripleWitching build          # produce build/ first
//   node design/make_replay_harness.mjs
//
// then serve build-replaytest/ and open one of the URLs it prints.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUILD = path.join(appRoot, 'build');
const OUT = path.join(appRoot, 'build-replaytest');
const DATA = path.join(appRoot, 'src/stories/data');

if (!fs.existsSync(BUILD)) {
	console.error(`no build at ${BUILD} — run the app build first`);
	process.exit(1);
}

// The books are TS modules with a single array literal; take the literal and
// parse it as JSON rather than importing (no TS loader needed).
const readBooks = (file) => {
	const full = path.join(DATA, file);
	if (!fs.existsSync(full)) return [];
	const text = fs.readFileSync(full, 'utf8');
	const start = text.indexOf('[');
	const end = text.lastIndexOf(']');
	if (start < 0 || end < 0) throw new Error(`no array literal in ${file}`);
	return JSON.parse(text.slice(start, end + 1));
};

const books = {
	base: readBooks('base_books.ts'),
	bonus: readBooks('bonus_books.ts'),
};

// ── copy the build ───────────────────────────────────────────────────────────
fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(BUILD, OUT, { recursive: true });

// ── mock data ────────────────────────────────────────────────────────────────
// Only what the replay response needs: the book events become `state`, and the
// multiplier drives the figures on the start card.
const mockData = Object.fromEntries(
	Object.entries(books).map(([mode, list]) => [
		mode,
		list.map((book) => ({
			id: book.id,
			payoutMultiplier: book.payoutMultiplier,
			state: book.events,
		})),
	]),
);
fs.writeFileSync(path.join(OUT, 'replay-mock-data.json'), JSON.stringify(mockData));

// ── service worker ───────────────────────────────────────────────────────────
const sw = `// Generated by design/make_replay_harness.mjs — do not edit, do not ship.
const API_AMOUNT_MULTIPLIER = 1000000;
let dataPromise = null;
const getData = () => {
	if (!dataPromise) dataPromise = fetch('./replay-mock-data.json').then((r) => r.json());
	return dataPromise;
};

self.addEventListener('install', (e) => e.waitUntil(self.skipWaiting()));
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));

self.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);
	if (!url.pathname.includes('/bet/replay/')) return;

	event.respondWith(
		(async () => {
			// /bet/replay/{game}/{version}/{mode}/{event}
			const parts = url.pathname.split('/').filter(Boolean);
			const mode = (parts[parts.length - 2] || 'base').toLowerCase();
			const index = Number(parts[parts.length - 1]) || 0;

			const data = await getData();
			const list = data[mode] || data.base || [];
			const book = list[index % Math.max(list.length, 1)];

			if (!book) {
				return new Response(JSON.stringify({ error: 'no mock book for mode ' + mode }), {
					status: 200,
					headers: { 'content-type': 'application/json' },
				});
			}

			// The page's ?amount= is the stake the replay was recorded at; payout has
			// to be expressed against it or the start card's Total Win is wrong.
			let amount = API_AMOUNT_MULTIPLIER;
			try {
				const client = await self.clients.get(event.clientId);
				if (client) amount = Number(new URL(client.url).searchParams.get('amount')) || amount;
			} catch (e) {}

			const body = {
				id: book.id,
				payoutMultiplier: book.payoutMultiplier,
				payout: book.payoutMultiplier * amount,
				state: book.state,
			};

			console.log('[replay-mock]', mode, 'book', book.id, 'x' + book.payoutMultiplier);

			return new Response(JSON.stringify(body), {
				status: 200,
				headers: { 'content-type': 'application/json' },
			});
		})(),
	);
});
`;
fs.writeFileSync(path.join(OUT, 'replay-mock-sw.js'), sw);

// ── register the worker before the app boots ─────────────────────────────────
// The first load of a page is not controlled by a worker it registers itself, so
// the snippet reloads once as soon as the worker is active. Without that the
// app's replay request would go to the real network on the very load being
// tested.
const REGISTER = `		<script>
			// replay test harness — injected by design/make_replay_harness.mjs
			//
			// Frame pump. Browsers throttle requestAnimationFrame to ZERO in a hidden
			// or backgrounded tab, and every animation in this game is rAF-driven —
			// the reels, the win rings, the transition, even FadeContainer's alpha
			// tween, which means the backdrop containers never so much as mount. An
			// automated check driving this page therefore sees a permanently frozen
			// first frame and cannot tell a broken animation from a paused one.
			//
			// Opting in with ?pump=1 swaps rAF for a timer so the page animates
			// regardless of visibility. It is deliberately opt-in and lives only in
			// build-replaytest/, which is gitignored and never shipped: a timer is
			// not a frame clock and must not be what a human judges timing on.
			if (new URLSearchParams(location.search).get('pump') === '1') {
				let id = 0;
				const pending = new Map();
				window.requestAnimationFrame = (cb) => {
					const handle = ++id;
					pending.set(handle, setTimeout(() => { pending.delete(handle); cb(performance.now()); }, 16));
					return handle;
				};
				window.cancelAnimationFrame = (handle) => {
					clearTimeout(pending.get(handle));
					pending.delete(handle);
				};
			}
			if ('serviceWorker' in navigator) {
				navigator.serviceWorker.register('./replay-mock-sw.js', { scope: './' }).then(async () => {
					await navigator.serviceWorker.ready;
					if (!navigator.serviceWorker.controller) location.reload();
				});
			}
		</script>
`;

const indexPath = path.join(OUT, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replace('<head>', `<head>\n${REGISTER}`);
fs.writeFileSync(indexPath, html);

// ── report ───────────────────────────────────────────────────────────────────
const counts = Object.entries(mockData)
	.map(([m, l]) => `${m}=${l.length}`)
	.join(' ');
console.log(`harness written to ${OUT} (books: ${counts})`);
console.log('\nserve it, then open:');
for (const [mode, list] of Object.entries(mockData)) {
	list.forEach((book, i) => {
		console.log(
			`  ${mode} x${book.payoutMultiplier}\n` +
				`    http://localhost:4174/?replay=true&rgs_url=mock.local&game=TripleWitching&version=1` +
				`&mode=${mode}&event=${i}&amount=1000000&currency=USD&language=en`,
		);
	});
}
