import { setFontKit, setLocalFonts } from 'pixi-svelte';

import { isCoveredByDisplayFont } from './fontCoverage';

// Ember Forge ships one self-hosted display face.
//
// History: the Stake template pulled `proxima-nova` from Adobe Typekit via a
// <link> in app.html. That kit is locked to the template's account, so on any
// other origin it 404s and every Text silently fell back to Arial. The first fix
// was to drop webfonts altogether and run on the system stack — which removed
// the 404, but certification then flagged "standard fonts", correctly: a slot
// rendered in Trebuchet/Segoe reads as operating-system UI, not as a game.
//
// Titan One is the answer to both. It is self-hosted (no third-party request to
// break), SIL Open Font Licence (commercial use and embedding permitted, see
// static/fonts/TitanOne-OFL.txt), and its heavy rounded forms are the display
// idiom players expect from a slot. Chosen over the other candidates because its
// digits stay legible at bet-bar size and fit inside the 603x135 brass readout
// plate without crowding — see design/font_candidates.png and font_incontext.png
// for the comparison this was picked from.
// Ember Runic sits in FRONT of Titan One rather than replacing it, and that is
// load-bearing rather than cautious. Ember Runic is Latin, digits and
// punctuation only — the game ships 16 locales including Japanese, Korean,
// Chinese, Arabic and Hindi. Browsers resolve a font stack PER CHARACTER, so
// Latin text is carved and every other script drops straight through to the
// faces behind it. Dropping Titan One would leave those locales on whatever
// sans the OS happens to supply.
//
// Generated by design/generate_font.mjs — original work, so unlike a licensed
// face there is nothing to attribute or renew.
export const GAME_FONT =
	'"Ember Runic", "Titan One", "Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

// The title face: the same skeleton cut as Roman inscriptional capitals rather
// than as runes — a bar across every free stroke end, which is what a chisel
// actually leaves and what makes carved Latin read as ancient rather than as
// stylised. Generated by the same script with --inscribed.
//
// Used only where a few words carry the whole mood — the loading screen title
// and its prompt. NOT for the interface: the serifs cost legibility at bet-bar
// size, which is the size most of this game's text is set at, and the runic face
// was chosen for exactly that reason. Same fallbacks behind it, so non-Latin
// scripts drop through per character just as they do for GAME_FONT.
export const TITLE_FONT =
	'"Ember Inscribed", "Ember Runic", "Titan One", "Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

// Titan One is a single-weight family. Asking for 700 makes the browser
// synthesise a bold by smearing the outline, which on a face this heavy just
// turns counters to mud — so anything using GAME_FONT must request 400.
export const GAME_FONT_WEIGHT = '400' as const;

// Display faces are for display. The rules and paytable modals carry real
// paragraphs — the RTP disclaimer, the feature descriptions — and setting body
// copy in a heavy rounded face makes it genuinely harder to read. Those keep a
// plain humanist stack. Two faces with clearly separated jobs is the normal
// arrangement, not a compromise.
export const BODY_FONT = '"Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

/**
 * The display face for this string — but only if it can draw all of it.
 *
 * The fallbacks written into GAME_FONT and TITLE_FONT above look like they
 * handle non-Latin scripts, and per character they do. That is the problem:
 * browsers fall back PER GLYPH, so Polish "SIATKA ŻARU" comes out as SIATKA
 * ARU in the carved face with a single Ż from something else — two faces, two
 * weights, inside one word. It reads as a rendering bug.
 *
 * So localised strings ask this instead of naming a face. A line the generated
 * faces cannot set completely is set entirely in the body stack, which is
 * duller and correct. See src/game/fontCoverage.ts for the table, emitted from
 * the fonts themselves by design/check_font_coverage.mjs.
 */
export const displayFontFor = (text: string): string =>
	isCoveredByDisplayFont(text) ? GAME_FONT : BODY_FONT;

/**
 * The title face, under the same rule. Same reasoning as displayFontFor; kept
 * separate because the two faces are used in different places and a caller
 * should not have to know they share a coverage table.
 */
export const titleFontFor = (text: string): string =>
	isCoveredByDisplayFont(text) ? TITLE_FONT : BODY_FONT;

/**
 * Weight to pair with either of the above. The generated faces are
 * single-weight and must be asked for 400 (see GAME_FONT_WEIGHT), but the body
 * stack is a normal family and needs real weight to hold up as a display line.
 */
export const displayWeightFor = (text: string): '400' | '700' =>
	isCoveredByDisplayFont(text) ? GAME_FONT_WEIGHT : '700';

// The rules and paytable modals are DOM, not Pixi, so they take their type from
// CSS. Mirroring both stacks into custom properties lets components/ui/Modals
// apply them without keeping a second copy of the font lists in SCSS — the
// shared components still declare the template's dead 'proxima-nova', which
// resolves to whatever sans the browser defaults to.
if (typeof document !== 'undefined') {
	const root = document.documentElement.style;
	root.setProperty('--gb-display-font', GAME_FONT);
	root.setProperty('--gb-body-font', BODY_FONT);
}

// Skip the template's Typekit request: nothing here needs it, and it removes
// both the 404 and the "Web font load inactive" console error.
setFontKit(null);

// Block startup until Titan One is actually resident. Pixi measures glyph
// advances when it builds a Text, so a face still downloading at that moment
// gets the first frame laid out on the fallback's metrics and never re-measured.
// Module scope, so this runs well before InitialiseApplication mounts.
setLocalFonts([
	`${GAME_FONT_WEIGHT} 16px "Ember Runic"`,
	`${GAME_FONT_WEIGHT} 16px "Ember Inscribed"`,
	`${GAME_FONT_WEIGHT} 16px "Titan One"`,
]);
