// GENERATED by design/check_font_coverage.mjs --emit — do not edit by hand.
//
// What the display faces can actually draw: the INTERSECTION of EmberRunic and
// EmberInscribed's cmaps, since a string may be set in either.
//
// This matters because browsers fall back PER GLYPH. Ask for Ember Runic and set
// the Polish "SIATKA ŻARU" in it and you get SIATKA - ARU in the display face and
// Ż in whatever the fallback is: two faces inside one word. That reads as a
// rendering bug and is strictly worse than setting the whole line in one plain
// face — which is what fonts.ts does instead, using this table.
const COVERED: readonly (readonly [number, number])[] = [
	[0x0020, 0x0021],
	[0x0023, 0x0025],
	[0x0027, 0x003b],
	[0x003d, 0x003d],
	[0x003f, 0x003f],
	[0x0041, 0x005a],
	[0x0061, 0x007a],
	[0x00a2, 0x00a3],
	[0x00a5, 0x00a5],
	[0x00b7, 0x00b7],
	[0x00c0, 0x00c2],
	[0x00c4, 0x00c4],
	[0x00c7, 0x00c7],
	[0x00c9, 0x00c9],
	[0x00cd, 0x00cd],
	[0x00d2, 0x00d2],
	[0x00d6, 0x00d7],
	[0x00d9, 0x00d9],
	[0x00dc, 0x00dc],
	[0x00e0, 0x00e2],
	[0x00e4, 0x00e4],
	[0x00e7, 0x00e7],
	[0x00e9, 0x00e9],
	[0x00ed, 0x00ed],
	[0x00f2, 0x00f2],
	[0x00f6, 0x00f6],
	[0x00f9, 0x00f9],
	[0x00fc, 0x00fc],
	[0x0104, 0x0107],
	[0x0110, 0x0111],
	[0x0130, 0x0130],
	[0x0141, 0x0142],
	[0x015a, 0x015b],
	[0x015e, 0x015f],
	[0x01af, 0x01b0],
	[0x1ea0, 0x1ea1],
	[0x1ea4, 0x1ea5],
	[0x1eae, 0x1eaf],
	[0x1ebe, 0x1ebf],
	[0x1ec2, 0x1ec5],
	[0x1ed4, 0x1ed5],
	[0x1ee2, 0x1ee5],
	[0x1ef2, 0x1ef3],
	[0x2013, 0x2014],
	[0x2018, 0x2019],
	[0x201c, 0x201d],
	[0x20ac, 0x20ac],
];

export const isCoveredByDisplayFont = (text: string): boolean => {
	for (const ch of text) {
		const code = ch.codePointAt(0);
		if (code === undefined) continue;
		// A space is drawn by nothing and breaks no word.
		if (code === 0x20) continue;
		if (!COVERED.some(([lo, hi]) => code >= lo && code <= hi)) return false;
	}
	return true;
};
