// GENERATED by design/generate_lava_flow.mjs — do not edit by hand.
//
// Points on bg_background.png that are actually on fire, in scene-normalised
// coordinates (0..1 across the painting, NOT across the canvas). Background.svelte
// seeds its drifting embers here so sparks come off the furnace, the cauldron and
// the dragon's pour instead of rising out of the flagstones.
export type HeatPoint = { x: number; y: number; heat: number };

export const HEAT_POINTS: HeatPoint[] = [
	{ x: 0.5182, y: 0.0625, heat: 0.54 },
	{ x: 0.4661, y: 0.0723, heat: 1.00 },
	{ x: 0.5221, y: 0.0781, heat: 1.00 },
	{ x: 0.7305, y: 0.0781, heat: 0.45 },
	{ x: 0.5911, y: 0.0840, heat: 0.63 },
	{ x: 0.4974, y: 0.0957, heat: 1.00 },
	{ x: 0.7565, y: 0.1113, heat: 0.86 },
	{ x: 0.2969, y: 0.1328, heat: 0.99 },
	{ x: 0.5690, y: 0.1328, heat: 1.00 },
	{ x: 0.6354, y: 0.1328, heat: 1.00 },
	{ x: 0.4831, y: 0.1348, heat: 0.69 },
	{ x: 0.2865, y: 0.1367, heat: 0.96 },
	{ x: 0.6068, y: 0.1367, heat: 0.87 },
	{ x: 0.4870, y: 0.1387, heat: 0.75 },
	{ x: 0.7266, y: 0.1621, heat: 0.69 },
	{ x: 0.7344, y: 0.1797, heat: 1.00 },
	{ x: 0.4609, y: 0.1855, heat: 1.00 },
	{ x: 0.5000, y: 0.2148, heat: 0.84 },
	{ x: 0.2266, y: 0.2422, heat: 0.51 },
	{ x: 0.0846, y: 0.2793, heat: 0.96 },
	{ x: 0.2357, y: 0.2891, heat: 0.51 },
	{ x: 0.7435, y: 0.3770, heat: 1.00 },
	{ x: 0.2461, y: 0.3809, heat: 0.75 },
	{ x: 0.2591, y: 0.4668, heat: 0.49 },
	{ x: 0.7565, y: 0.4746, heat: 0.90 },
	{ x: 0.1016, y: 0.4941, heat: 0.73 },
	{ x: 0.1432, y: 0.4980, heat: 0.79 },
	{ x: 0.1380, y: 0.5039, heat: 0.55 },
	{ x: 0.1471, y: 0.5078, heat: 0.86 },
	{ x: 0.7383, y: 0.5098, heat: 0.55 },
	{ x: 0.7461, y: 0.5117, heat: 1.00 },
	{ x: 0.1120, y: 0.5137, heat: 0.92 },
	{ x: 0.2604, y: 0.5215, heat: 0.47 },
	{ x: 0.1458, y: 0.5313, heat: 0.84 },
	{ x: 0.1471, y: 0.5488, heat: 0.90 },
	{ x: 0.1159, y: 0.5684, heat: 0.76 },
	{ x: 0.7448, y: 0.6426, heat: 0.85 },
	{ x: 0.7826, y: 0.6719, heat: 0.97 },
	{ x: 0.8346, y: 0.6758, heat: 0.70 },
	{ x: 0.8073, y: 0.7070, heat: 1.00 },
	{ x: 0.8034, y: 0.7129, heat: 1.00 },
	{ x: 0.8138, y: 0.7148, heat: 1.00 },
	{ x: 0.2409, y: 0.7168, heat: 0.78 },
	{ x: 0.6979, y: 0.9414, heat: 0.88 },
];
