// Generated by design/sync_story_books.py from books_bonus.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L4"
    },
    {
     "name": "H3"
    },
    {
     "name": "H5"
    },
    {
     "name": "L1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "L3"
    },
    {
     "name": "H2"
    },
    {
     "name": "H5"
    },
    {
     "name": "L1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "H4"
    }
   ],
   [
    {
     "name": "L2"
    },
    {
     "name": "H4"
    },
    {
     "name": "L1"
    },
    {
     "name": "H2"
    },
    {
     "name": "L3"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "C",
     "collector": true
    },
    {
     "name": "H4"
    },
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "L4"
    },
    {
     "name": "H4"
    },
    {
     "name": "L4"
    }
   ]
  ],
  "paddingPositions": [
   12,
   52,
   23,
   40,
   5
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   1,
   2,
   3
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 4
   },
   {
    "reel": 1,
    "row": 4
   },
   {
    "reel": 2,
    "row": 3
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "neon_nights",
  "seedFrames": 1
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "newFrames": {
  "index": 6,
  "type": "newFrames",
  "frames": [
   {
    "reel": 3,
    "row": 3,
    "mult": 8
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 2
   },
   {
    "reel": 4,
    "row": 2,
    "mult": 2
   }
  ]
 },
 "updateFrames": {
  "index": 10,
  "type": "updateFrames",
  "frames": [
   {
    "reel": 3,
    "row": 3,
    "mult": 2
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 4,
    "row": 2,
    "mult": 2
   }
  ]
 },
 "winInfo": {
  "index": 16,
  "type": "winInfo",
  "totalWin": 400,
  "wins": [
   {
    "symbol": "L2",
    "kind": 4,
    "win": 400,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 3
     },
     {
      "reel": 3,
      "row": 3
     }
    ],
    "meta": {
     "lineIndex": 3,
     "multiplier": 4,
     "winWithoutMult": 100,
     "globalMult": 1,
     "lineMultiplier": 4
    }
   }
  ]
 },
 "setWin": {
  "index": 17,
  "type": "setWin",
  "amount": 400,
  "winLevel": 4
 },
 "collectorWin": {
  "index": 45,
  "type": "collectorWin",
  "position": {
   "reel": 3,
   "row": 1
  },
  "frames": [
   {
    "reel": 3,
    "row": 3,
    "mult": 4
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 4,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 1,
    "row": 1,
    "mult": 4
   },
   {
    "reel": 1,
    "row": 3,
    "mult": 9
   }
  ],
  "totalMultiplier": 23,
  "amount": 2300
 },
 "freeSpinRetrigger": {
  "index": 57,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 0,
    "row": 3
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 },
 "freeSpinEnd": {
  "index": 67,
  "type": "freeSpinEnd",
  "amount": 3780,
  "winLevel": 5
 },
 "finalWin": {
  "index": 68,
  "type": "finalWin",
  "amount": 3780
 }
};
