// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    },
    {
     "name": "H5"
    }
   ],
   [
    {
     "name": "H3"
    },
    {
     "name": "H5"
    },
    {
     "name": "L4"
    },
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "H2"
    },
    {
     "name": "H3"
    }
   ],
   [
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "H4"
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "H3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H5"
    }
   ]
  ],
  "paddingPositions": [
   15,
   22,
   26,
   24,
   23
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   1
  ]
 },
 "winInfo": {
  "index": 1,
  "type": "winInfo",
  "totalWin": 80,
  "wins": [
   {
    "symbol": "L3",
    "kind": 3,
    "win": 40,
    "positions": [
     {
      "reel": 0,
      "row": 2
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 4
     }
    ],
    "meta": {
     "lineIndex": 6,
     "multiplier": 1,
     "winWithoutMult": 40,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   },
   {
    "symbol": "L3",
    "kind": 3,
    "win": 40,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 4
     }
    ],
    "meta": {
     "lineIndex": 14,
     "multiplier": 1,
     "winWithoutMult": 40,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 2,
  "type": "setWin",
  "amount": 80,
  "winLevel": 2
 },
 "setTotalWin": {
  "index": 3,
  "type": "setTotalWin",
  "amount": 80
 },
 "freeSpinTrigger": {
  "index": 4,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 1
   },
   {
    "reel": 3,
    "row": 4
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 },
 "bonusTier": {
  "index": 5,
  "type": "bonusTier",
  "tier": "neon_nights",
  "seedFrames": 1
 },
 "updateFreeSpin": {
  "index": 6,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "newFrames": {
  "index": 8,
  "type": "newFrames",
  "frames": [
   {
    "reel": 1,
    "row": 2,
    "mult": 2
   },
   {
    "reel": 1,
    "row": 3,
    "mult": 3
   },
   {
    "reel": 3,
    "row": 4,
    "mult": 8
   }
  ]
 },
 "updateFrames": {
  "index": 12,
  "type": "updateFrames",
  "frames": [
   {
    "reel": 1,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 1,
    "row": 3,
    "mult": 4
   },
   {
    "reel": 3,
    "row": 4,
    "mult": 2
   }
  ]
 },
 "freeSpinEnd": {
  "index": 58,
  "type": "freeSpinEnd",
  "amount": 28520,
  "winLevel": 7
 },
 "finalWin": {
  "index": 59,
  "type": "finalWin",
  "amount": 28600
 },
 "collectorWin": {
  "index": 2,
  "type": "collectorWin",
  "position": {
   "reel": 0,
   "row": 1
  },
  "frames": [
   {
    "reel": 4,
    "row": 1,
    "mult": 7
   },
   {
    "reel": 1,
    "row": 3,
    "mult": 4
   }
  ],
  "totalMultiplier": 11,
  "amount": 1100
 },
 "freeSpinRetrigger": {
  "index": 12,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 0,
    "row": 3
   },
   {
    "reel": 2,
    "row": 4
   }
  ]
 },
 "frameDoubling": {
  "index": 40,
  "type": "frameDoubling",
  "frames": [
   {
    "reel": 1,
    "row": 2,
    "mult": 8
   }
  ]
 }
};
