// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L4"
    },
    {
     "name": "H1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L2"
    },
    {
     "name": "L3"
    },
    {
     "name": "H5"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H3"
    },
    {
     "name": "H4"
    },
    {
     "name": "L4"
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    },
    {
     "name": "H3"
    },
    {
     "name": "H4"
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "L2"
    },
    {
     "name": "H4"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H1"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "C",
     "collector": true
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L3"
    }
   ]
  ],
  "paddingPositions": [
   36,
   11,
   36,
   54,
   36
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   1,
   2
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 2
   },
   {
    "reel": 2,
    "row": 2
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "neon_nights",
  "seedFrames": 1
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "newFrames": {
  "index": 6,
  "type": "newFrames",
  "frames": [
   {
    "reel": 4,
    "row": 1,
    "mult": 2
   }
  ]
 },
 "collectorWin": {
  "index": 7,
  "type": "collectorWin",
  "position": {
   "reel": 1,
   "row": 1
  },
  "frames": [
   {
    "reel": 4,
    "row": 1,
    "mult": 2
   }
  ],
  "totalMultiplier": 2,
  "amount": 200
 },
 "winInfo": {
  "index": 8,
  "type": "winInfo",
  "totalWin": 200,
  "wins": [
   {
    "symbol": "C",
    "kind": 1,
    "win": 200,
    "positions": [
     {
      "reel": 1,
      "row": 1
     }
    ],
    "meta": {
     "lineIndex": 0,
     "multiplier": 2,
     "winWithoutMult": 100,
     "globalMult": 1,
     "lineMultiplier": 2,
     "collector": true
    }
   }
  ]
 },
 "setWin": {
  "index": 9,
  "type": "setWin",
  "amount": 200,
  "winLevel": 4
 },
 "updateFrames": {
  "index": 13,
  "type": "updateFrames",
  "frames": [
   {
    "reel": 4,
    "row": 1,
    "mult": 7
   }
  ]
 },
 "freeSpinRetrigger": {
  "index": 69,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 2,
    "row": 4
   },
   {
    "reel": 3,
    "row": 1
   }
  ]
 },
 "freeSpinEnd": {
  "index": 82,
  "type": "freeSpinEnd",
  "amount": 7780,
  "winLevel": 6
 },
 "finalWin": {
  "index": 83,
  "type": "finalWin",
  "amount": 7780
 },
 "frameDoubling": {
  "index": 49,
  "type": "frameDoubling",
  "frames": [
   {
    "reel": 0,
    "row": 3,
    "mult": 4
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 6
   }
  ]
 }
};
