// Generated by design/sync_story_books.py from books_bonus.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L2"
    },
    {
     "name": "L4"
    },
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    },
    {
     "name": "H2"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "C",
     "collector": true
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "L4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L2"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "H2"
    }
   ],
   [
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    }
   ]
  ],
  "paddingPositions": [
   7,
   14,
   4,
   25,
   16
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   1
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 1,
    "row": 3
   },
   {
    "reel": 3,
    "row": 3
   },
   {
    "reel": 4,
    "row": 3
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "neon_nights",
  "seedFrames": 1
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "newFrames": {
  "index": 6,
  "type": "newFrames",
  "frames": [
   {
    "reel": 2,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 2
   }
  ]
 },
 "winInfo": {
  "index": 7,
  "type": "winInfo",
  "totalWin": 40,
  "wins": [
   {
    "symbol": "L3",
    "kind": 3,
    "win": 40,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 3
     }
    ],
    "meta": {
     "lineIndex": 3,
     "multiplier": 1,
     "winWithoutMult": 40,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "collectorWin": {
  "index": 8,
  "type": "collectorWin",
  "position": {
   "reel": 2,
   "row": 1
  },
  "frames": [
   {
    "reel": 2,
    "row": 2,
    "mult": 3
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 2
   }
  ],
  "totalMultiplier": 5,
  "amount": 500
 },
 "setWin": {
  "index": 10,
  "type": "setWin",
  "amount": 540,
  "winLevel": 5
 },
 "updateFrames": {
  "index": 14,
  "type": "updateFrames",
  "frames": [
   {
    "reel": 2,
    "row": 2,
    "mult": 4
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 8
   }
  ]
 },
 "freeSpinEnd": {
  "index": 66,
  "type": "freeSpinEnd",
  "amount": 13640,
  "winLevel": 7
 },
 "finalWin": {
  "index": 67,
  "type": "finalWin",
  "amount": 13640
 },
 "freeSpinRetrigger": {
  "index": 26,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 3,
    "row": 3
   },
   {
    "reel": 4,
    "row": 1
   }
  ]
 }
};
