"""Regenerate Storybook fixture books from the Hot Miami math output.

The stories replay real book event streams through the renderer. If these
fixtures come from a different game, the runner awaits a handler that does not
exist in bookEventHandlerMap and the story hangs forever with no console error.
"""

import json
import random
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PUBLISH = ROOT.parent / "math-sdk/games/hot_miami/library/publish_files"
OUT = Path(__file__).resolve().parent.parent / "src/stories/data"

SAMPLE_COUNT = 12


def read_books(mode: str) -> list:
    raw = subprocess.run(
        ["zstd", "-dc", str(PUBLISH / f"books_{mode}.jsonl.zst")],
        capture_output=True,
        check=True,
    ).stdout.decode()
    return [json.loads(line) for line in raw.splitlines() if line.strip()]


def sample(books: list, want_win: bool) -> list:
    pool = [b for b in books if (b["payoutMultiplier"] > 0) == want_win]
    random.seed(7)
    return random.sample(pool, min(SAMPLE_COUNT, len(pool)))


def write_books(name: str, books: list, header: str) -> None:
    body = json.dumps(books, indent=1)
    (OUT / f"{name}_books.ts").write_text(f"// {header}\nexport default {body};\n")


def write_events(name: str, books: list, header: str) -> None:
    first: dict = {}
    for book in books:
        for event in book["events"]:
            first.setdefault(event["type"], event)
    body = json.dumps(first, indent=1)
    (OUT / f"{name}_events.ts").write_text(f"// {header}\nexport default {body};\n")


def main() -> None:
    for name, mode, want_win in [("base", "base", True), ("bonus", "bonus", True)]:
        books = sample(read_books(mode), want_win)
        header = f"Generated by design/sync_story_books.py from books_{mode}.jsonl.zst — do not edit by hand."
        write_books(name, books, header)
        write_events(name, books, header)
        types = sorted({e["type"] for b in books for e in b["events"]})
        print(f"{name}: {len(books)} books, events: {', '.join(types)}")


if __name__ == "__main__":
    main()
