// Deadwood runtime assets only. Legacy keys are internal aliases, not source art.
export default {
 dwBackground: {type: 'sprite', src: './assets/deadwood/background.png', preload: true},
 dwBackgroundFeature: {type: 'sprite', src: './assets/deadwood/background_feature.png', preload: true},
 dwBonusButton: {type: 'sprite', src: './assets/deadwood/bonus_button.png', preload: true},
 fxGlow: {type: 'sprite', src: './assets/deadwood/fx_glow.png', preload: true},
 fxStar: {type: 'sprite', src: './assets/deadwood/fx_star.png', preload: true},
 fxStreak: {type: 'sprite', src: './assets/deadwood/fx_streak.png', preload: true},
 fxLeaf: {type: 'sprite', src: './assets/deadwood/fx_leaf.png', preload: true},
 fxVignette: {type: 'sprite', src: './assets/deadwood/fx_vignette.png', preload: true},
 hmWinBannerBig: {type: 'sprite', src: './assets/deadwood/win_big.svg', preload: true},
 hmWinBannerSuperwin: {type: 'sprite', src: './assets/deadwood/win_superwin.svg', preload: true},
 hmWinBannerMega: {type: 'sprite', src: './assets/deadwood/win_mega.svg', preload: true},
 hmWinBannerEpic: {type: 'sprite', src: './assets/deadwood/win_epic.svg', preload: true},
 hmWinBannerMax: {type: 'sprite', src: './assets/deadwood/win_max.svg', preload: true},
 hmFsSign: {type: 'sprite', src: './assets/deadwood/fs_sign.svg', preload: true},
 hmFsPanel: {type: 'sprite', src: './assets/deadwood/fs_panel.svg', preload: true},
 hmH1: {type: 'sprite', src: './assets/deadwood/symbol_H1.png', preload: true},
 hmH2: {type: 'sprite', src: './assets/deadwood/symbol_H2.png', preload: true},
 hmH3: {type: 'sprite', src: './assets/deadwood/symbol_H3.png', preload: true},
 hmH4: {type: 'sprite', src: './assets/deadwood/symbol_H4.png', preload: true},
 hmH5: {type: 'sprite', src: './assets/deadwood/symbol_H5.png', preload: true},
 hmL1: {type: 'sprite', src: './assets/deadwood/symbol_L1.png', preload: true},
 hmL2: {type: 'sprite', src: './assets/deadwood/symbol_L2.png', preload: true},
 hmL3: {type: 'sprite', src: './assets/deadwood/symbol_L3.png', preload: true},
 hmL4: {type: 'sprite', src: './assets/deadwood/symbol_L4.png', preload: true},
 hmW: {type: 'sprite', src: './assets/deadwood/symbol_W.png', preload: true},
 hmS: {type: 'sprite', src: './assets/deadwood/symbol_S.png', preload: true},
 hmC: {type: 'sprite', src: './assets/deadwood/symbol_S.png', preload: true},
 hmFrame: {type: 'sprite', src: './assets/deadwood/bonus_button.png', preload: true},
 hmCCoreActive: {type: 'sprite', src: './assets/deadwood/fx_glow.png', preload: true},
 hmLogo: {type: 'sprite', src: './assets/deadwood/logo.png', preload: true},
 hmCastGuyMesh: {type: 'sprite', src: './assets/deadwood/conductor.png', preload: true},
 hmIconMenu: {type: 'sprite', src: './assets/deadwood/icon_menu.svg', preload: true},
 hmIconMenuExit: {type: 'sprite', src: './assets/deadwood/icon_menuExit.svg', preload: true},
 hmIconSettings: {type: 'sprite', src: './assets/deadwood/icon_settings.svg', preload: true},
 hmIconInfo: {type: 'sprite', src: './assets/deadwood/icon_info.svg', preload: true},
 hmIconPayTable: {type: 'sprite', src: './assets/deadwood/icon_payTable.svg', preload: true},
 hmIconSoundOn: {type: 'sprite', src: './assets/deadwood/icon_soundOn.svg', preload: true},
 hmIconSoundOff: {type: 'sprite', src: './assets/deadwood/icon_soundOff.svg', preload: true},
 hmIconAutoSpin: {type: 'sprite', src: './assets/deadwood/icon_autoSpin.svg', preload: true},
 coins: {type:'spriteSheet',src:'./assets/sprites/coin/coin.json'},
 sound: {type:'audio',src:'./assets/audio/sounds.json',preload:true},
} as const;
