import { setFontKit, setLocalFonts } from 'pixi-svelte';

// Crusher Yard ships one self-hosted display face.
//
// History: the Stake template pulled `proxima-nova` from Adobe Typekit via a
// <link> in app.html. That kit is locked to the template's account, so on any
// other origin it 404s and every Text silently fell back to Arial. The first fix
// was to drop webfonts altogether and run on the system stack — which removed
// the 404, but certification then flagged "standard fonts", correctly: a slot
// rendered in Trebuchet/Segoe reads as operating-system UI, not as a game.
//
// Titan One is the answer to both. It is self-hosted (no third-party request to
// break), SIL Open Font Licence (commercial use and embedding permitted, see
// static/fonts/TitanOne-OFL.txt), and its heavy rounded forms are the display
// idiom players expect from a slot. Chosen over the other candidates because its
// digits stay legible at bet-bar size and fit inside the 603x135 brass readout
// plate without crowding — see design/font_candidates.png and font_incontext.png
// for the comparison this was picked from.
// Yard Plate sits in FRONT of Titan One rather than replacing it, and that is
// load-bearing rather than cautious. Yard Plate is Latin, digits and
// punctuation only — the game ships 16 locales including Japanese, Korean,
// Chinese, Arabic and Hindi. Browsers resolve a font stack PER CHARACTER, so
// Latin text is set in the plate face and every other script drops straight
// through to the faces behind it. Dropping Titan One would leave those locales
// on whatever sans the OS happens to supply.
//
// Generated by design/generate_font.mjs — original work, so unlike a licensed
// face there is nothing to attribute or renew.
export const GAME_FONT =
	'"Yard Plate", "Titan One", "Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

// The title face: the same skeleton with bridges cut through the strokes, the
// way a stencil plate has to be cut to hold its counters. Generated by the same
// script with --stencil.
//
// NOT for the interface, and this is the whole reason there are two faces
// rather than one. A bridged glyph at bet-bar size either closes up into a
// solid stroke — at which point the character is gone and the legibility was
// paid for nothing — or it reads as a broken letter. The one thing this font
// absolutely must render unambiguously is a balance, so the bridges live on the
// face that is only ever set large (52px loading title, 28px press-to-continue,
// the free-game outro heading) and the face doing the work stays solid.
//
// Same fallbacks behind it, so non-Latin scripts drop through per character just
// as they do for GAME_FONT.
export const TITLE_FONT =
	'"Yard Stencil", "Yard Plate", "Titan One", "Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

// Titan One is a single-weight family. Asking for 700 makes the browser
// synthesise a bold by smearing the outline, which on a face this heavy just
// turns counters to mud — so anything using GAME_FONT must request 400.
export const GAME_FONT_WEIGHT = '400' as const;

// Display faces are for display. The rules and paytable modals carry real
// paragraphs — the RTP disclaimer, the feature descriptions — and setting body
// copy in a heavy rounded face makes it genuinely harder to read. Those keep a
// plain humanist stack. Two faces with clearly separated jobs is the normal
// arrangement, not a compromise.
export const BODY_FONT = '"Trebuchet MS", "Segoe UI", Tahoma, Arial, sans-serif';

// The rules and paytable modals are DOM, not Pixi, so they take their type from
// CSS. Mirroring both stacks into custom properties lets components/ui/Modals
// apply them without keeping a second copy of the font lists in SCSS — the
// shared components still declare the template's dead 'proxima-nova', which
// resolves to whatever sans the browser defaults to.
if (typeof document !== 'undefined') {
	const root = document.documentElement.style;
	root.setProperty('--gb-display-font', GAME_FONT);
	root.setProperty('--gb-body-font', BODY_FONT);
}

// Skip the template's Typekit request: nothing here needs it, and it removes
// both the 404 and the "Web font load inactive" console error.
setFontKit(null);

// Block startup until Titan One is actually resident. Pixi measures glyph
// advances when it builds a Text, so a face still downloading at that moment
// gets the first frame laid out on the fallback's metrics and never re-measured.
// Module scope, so this runs well before InitialiseApplication mounts.
setLocalFonts([
	`${GAME_FONT_WEIGHT} 16px "Yard Plate"`,
	`${GAME_FONT_WEIGHT} 16px "Yard Stencil"`,
	`${GAME_FONT_WEIGHT} 16px "Titan One"`,
]);
