// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L4"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L2"
    },
    {
     "name": "L3"
    },
    {
     "name": "H2"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H3"
    },
    {
     "name": "L3"
    },
    {
     "name": "L4"
    },
    {
     "name": "L1"
    },
    {
     "name": "S",
     "scatter": true
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    },
    {
     "name": "H2"
    },
    {
     "name": "H4"
    }
   ],
   [
    {
     "name": "H4"
    },
    {
     "name": "L4"
    },
    {
     "name": "L3"
    },
    {
     "name": "H4"
    },
    {
     "name": "H2"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "H5"
    }
   ]
  ],
  "paddingPositions": [
   36,
   11,
   58,
   54,
   53
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   1,
   2
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 8,
  "positions": [
   {
    "reel": 0,
    "row": 2
   },
   {
    "reel": 2,
    "row": 2
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "lockdown",
  "seedLights": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 8
 },
 "searchlight": {
  "index": 6,
  "type": "searchlight",
  "lights": [
   {
    "reel": 1,
    "row": 1,
    "mult": 1,
    "cells": [
     {
      "reel": 1,
      "row": 1,
      "mult": 1,
      "doubled": false
     },
     {
      "reel": 1,
      "row": 2,
      "mult": 1,
      "doubled": false
     },
     {
      "reel": 1,
      "row": 3,
      "mult": 1,
      "doubled": false
     },
     {
      "reel": 1,
      "row": 4,
      "mult": 1,
      "doubled": false
     }
    ]
   }
  ],
  "reels": [
   1
  ]
 },
 "winInfo": {
  "index": 7,
  "type": "winInfo",
  "totalWin": 180,
  "wins": [
   {
    "symbol": "L3",
    "kind": 4,
    "win": 60,
    "positions": [
     {
      "reel": 0,
      "row": 2
     },
     {
      "reel": 1,
      "row": 2
     },
     {
      "reel": 2,
      "row": 2
     },
     {
      "reel": 3,
      "row": 2
     }
    ],
    "meta": {
     "lineIndex": 2,
     "multiplier": 1,
     "winWithoutMult": 60,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   },
   {
    "symbol": "H5",
    "kind": 3,
    "win": 60,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 4
     },
     {
      "reel": 2,
      "row": 4
     }
    ],
    "meta": {
     "lineIndex": 4,
     "multiplier": 1,
     "winWithoutMult": 60,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   },
   {
    "symbol": "H5",
    "kind": 3,
    "win": 60,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 4
     }
    ],
    "meta": {
     "lineIndex": 14,
     "multiplier": 1,
     "winWithoutMult": 60,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 8,
  "type": "setWin",
  "amount": 180,
  "winLevel": 3
 },
 "updateLights": {
  "index": 11,
  "type": "updateLights",
  "cells": [
   {
    "reel": 1,
    "row": 1,
    "mult": 1
   },
   {
    "reel": 1,
    "row": 2,
    "mult": 1
   },
   {
    "reel": 1,
    "row": 3,
    "mult": 1
   },
   {
    "reel": 1,
    "row": 4,
    "mult": 1
   }
  ]
 },
 "freeSpinEnd": {
  "index": 49,
  "type": "freeSpinEnd",
  "amount": 950,
  "winLevel": 3
 },
 "finalWin": {
  "index": 50,
  "type": "finalWin",
  "amount": 950
 }
};
