// Generated by design/sync_story_books.py from books_bonus.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L2"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    },
    {
     "name": "H3"
    }
   ],
   [
    {
     "name": "L3"
    },
    {
     "name": "L4"
    },
    {
     "name": "L1"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H4"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H4"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H2"
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "L1"
    },
    {
     "name": "H1"
    },
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H5"
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "W",
     "wild": true
    },
    {
     "name": "H4"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    }
   ]
  ],
  "paddingPositions": [
   7,
   13,
   4,
   33,
   8
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   1
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 8,
  "positions": [
   {
    "reel": 1,
    "row": 3
   },
   {
    "reel": 3,
    "row": 3
   },
   {
    "reel": 4,
    "row": 3
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "lockdown",
  "seedLights": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 8
 },
 "winInfo": {
  "index": 6,
  "type": "winInfo",
  "totalWin": 20,
  "wins": [
   {
    "symbol": "L3",
    "kind": 3,
    "win": 20,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 3
     }
    ],
    "meta": {
     "lineIndex": 3,
     "multiplier": 1,
     "winWithoutMult": 20,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 7,
  "type": "setWin",
  "amount": 20,
  "winLevel": 2
 },
 "searchlight": {
  "index": 11,
  "type": "searchlight",
  "lights": [
   {
    "reel": 0,
    "row": 1,
    "mult": 2,
    "cells": [
     {
      "reel": 0,
      "row": 1,
      "mult": 2,
      "doubled": false
     },
     {
      "reel": 0,
      "row": 2,
      "mult": 2,
      "doubled": false
     },
     {
      "reel": 0,
      "row": 3,
      "mult": 2,
      "doubled": false
     },
     {
      "reel": 0,
      "row": 4,
      "mult": 2,
      "doubled": false
     }
    ]
   }
  ],
  "reels": [
   0
  ]
 },
 "updateLights": {
  "index": 16,
  "type": "updateLights",
  "cells": [
   {
    "reel": 0,
    "row": 1,
    "mult": 2
   },
   {
    "reel": 0,
    "row": 2,
    "mult": 2
   },
   {
    "reel": 0,
    "row": 3,
    "mult": 2
   },
   {
    "reel": 0,
    "row": 4,
    "mult": 2
   }
  ]
 },
 "freeSpinRetrigger": {
  "index": 44,
  "type": "freeSpinRetrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 2,
    "row": 1
   },
   {
    "reel": 3,
    "row": 4
   }
  ]
 },
 "freeSpinEnd": {
  "index": 64,
  "type": "freeSpinEnd",
  "amount": 201020,
  "winLevel": 9
 },
 "finalWin": {
  "index": 65,
  "type": "finalWin",
  "amount": 201020
 }
};
