// Local PLAY test harness.
//
// Everything about this game has been verified in Storybook or by poking events
// into a dev server. Neither of those actually plays it: no stake, no balance, no
// round lifecycle, no Buy Bonus, no autoplay, no turbo — because all of that goes
// through an RGS that only Stake Engine serves. So the one thing nobody has done
// is press spin and watch a round happen end to end.
//
// The sibling GoBananas solved the same problem for replay only, with a service
// worker that answers /bet/replay from books in the repo. This extends that idea
// to the whole wallet API, so the game is genuinely playable offline:
//
//   /wallet/authenticate   balance + bet config + jurisdiction
//   /wallet/play           a real book for the requested mode
//   /wallet/end-round      settle
//   /bet/event             per-event ack
//
// A service worker rather than a stub server because rgs-fetcher hardcodes
// `https://${rgsUrl}` — a local stub would need a certificate the browser
// trusts, whereas a worker can answer a cross-origin request with a synthetic
// response and needs nothing but localhost.
//
// The shipped build is never touched: this writes only build-playtest/.
// It is a TEST RIG — do not upload it.
//
// Usage:
//   pnpm --dir apps/WildParty build
//   node design/make_play_harness.mjs
//   npx serve apps/WildParty/build-playtest    (or any static server)

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const BUILD = path.join(appRoot, 'build');
const OUT = path.join(appRoot, 'build-playtest');
const DATA = path.join(appRoot, 'src/stories/data');

if (!fs.existsSync(BUILD)) {
	console.error(`no build at ${BUILD} — run the app build first`);
	process.exit(1);
}

// The books are TS modules with a single array literal; take the literal and
// parse it as JSON rather than importing (no TS loader needed).
const readBooks = (file) => {
	const full = path.join(DATA, file);
	if (!fs.existsSync(full)) return [];
	const text = fs.readFileSync(full, 'utf8');
	const start = text.indexOf('[');
	const end = text.lastIndexOf(']');
	if (start < 0 || end < 0) throw new Error(`no array literal in ${file}`);
	return JSON.parse(text.slice(start, end + 1));
};

// Mode keys are what the client sends in /wallet/play. The three buy tiers all
// draw from the bonus books — the difference between them is cost and the
// multiplier the round opens on, both of which live inside the book.
const base = readBooks('base_books.ts');
const bonus = readBooks('bonus_books.ts');
const books = {
	BASE: base,
	BONUS: bonus,
	BONUS_QUICK: bonus,
	BONUS_SUPER: bonus,
};

const counts = Object.entries(books)
	.map(([k, v]) => `${k}:${v.length}`)
	.join(' ');
if (!base.length) {
	console.error('no base books found — nothing to play');
	process.exit(1);
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.cpSync(BUILD, OUT, { recursive: true });
fs.writeFileSync(
	path.join(OUT, 'play-mock-data.json'),
	JSON.stringify(
		Object.fromEntries(
			Object.entries(books).map(([mode, list]) => [
				mode,
				list.map((b) => ({ id: b.id, payoutMultiplier: b.payoutMultiplier, state: b.events })),
			]),
		),
	),
);

const sw = `// Generated by design/make_play_harness.mjs — do not edit, do not ship.
const M = 1000000; // API_AMOUNT_MULTIPLIER: 1,000,000 units = 1 coin

let dataPromise = null;
const getData = () => {
	if (!dataPromise) dataPromise = fetch('./play-mock-data.json').then((r) => r.json());
	return dataPromise;
};

// Wallet state, persisted through the Cache API.
//
// It was module-level variables first, which looked fine and was wrong: the
// browser kills an idle service worker and restarts it on the next request, so
// the balance silently reset to 1000 and the book cursor reset to 0 — every spin
// replayed the first book and the balance never moved past 999. A harness that
// always deals the same hand cannot show you a win, a free-spin round, or a
// bug. Cache is the only storage a worker has (no localStorage), so state goes
// there and is read back on every request.
const STATE_CACHE = 'wp-playtest-state';
const STATE_KEY = 'https://playtest.local/state';

const loadState = async () => {
	try {
		const cache = await caches.open(STATE_CACHE);
		const hit = await cache.match(STATE_KEY);
		if (hit) return await hit.json();
	} catch (e) {}
	return { balance: 1000 * M, spins: 0 };
};

const saveState = async (state) => {
	try {
		const cache = await caches.open(STATE_CACHE);
		await cache.put(STATE_KEY, new Response(JSON.stringify(state)));
	} catch (e) {}
};

let lastRound = null;

const json = (body) =>
	new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });

self.addEventListener('install', (e) => e.waitUntil(self.skipWaiting()));
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));

self.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);
	const p = url.pathname;
	const mine =
		p.includes('/wallet/authenticate') ||
		p.includes('/wallet/play') ||
		p.includes('/wallet/end-round') ||
		p.includes('/bet/event') ||
		p.includes('/bet/replay/');
	if (!mine) return;

	event.respondWith(
		(async () => {
			let body = {};
			try {
				body = await event.request.clone().json();
			} catch (e) {}

			const state = await loadState();

			// /bet/replay/{game}/{version}/{mode}/{event}
			//
			// Stake Engine only serves this for real historical bets, so replay mode
			// — playback, the replay-again button, and the state left behind between
			// runs — could not be exercised locally at all. That is exactly the part
			// certification reported broken.
			if (p.includes('/bet/replay/')) {
				const data = await getData();
				const parts = p.split('/').filter(Boolean);
				const mode = (parts[parts.length - 2] || 'BASE').toUpperCase();
				const index = Number(parts[parts.length - 1]) || 0;
				const list = data[mode] && data[mode].length ? data[mode] : data.BASE;
				const book = list[index % Math.max(list.length, 1)];
				if (!book) return json({ error: 'no mock book for mode ' + mode });

				// The page's ?amount= is the stake the replay was recorded at; the
				// payout has to be expressed against it or the displayed total is wrong.
				let amount = M;
				try {
					const client = await self.clients.get(event.clientId);
					if (client) amount = Number(new URL(client.url).searchParams.get('amount')) || amount;
				} catch (e) {}

				console.log('[replay-mock]', mode, 'book', book.id, 'x' + book.payoutMultiplier);
				return json({
					id: book.id,
					payoutMultiplier: book.payoutMultiplier,
					payout: book.payoutMultiplier * amount,
					state: book.state,
				});
			}

			if (p.includes('/wallet/authenticate')) {
				// ?mockBalance= (in API units) reproduces a specific balance. The Max
				// Bet defect certification reported only shows when the balance falls
				// BETWEEN two rungs of the ladder, so it needs to be set exactly.
				try {
					const client = await self.clients.get(event.clientId);
					const q = client && new URL(client.url).searchParams.get('mockBalance');
					if (q) {
						state.balance = Number(q);
						await saveState(state);
					}
				} catch (e) {}
				return json({
					balance: { amount: state.balance, currency: 'USD' },
					config: {
						gameID: 'wild-party-playtest',
						minBet: 0.1 * M,
						maxBet: 100 * M,
						stepBet: 0.1 * M,
						defaultBetLevel: 1 * M,
						betLevels: [0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100].map((v) => v * M),
						betModes: {},
						jurisdiction: {
							socialCasino: false,
							disabledFullscreen: false,
							disabledTurbo: false,
							disabledSuperTurbo: false,
							disabledAutoplay: false,
							disabledSlamstop: false,
							disabledSpacebar: false,
							disabledBuyFeature: false,
							displayNetPosition: false,
							displayRTP: false,
							displaySessionTimer: false,
							minimumRoundDuration: 0,
						},
					},
					// no active round on a fresh session
					round: null,
				});
			}

			if (p.includes('/wallet/play')) {
				const data = await getData();
				const mode = String(body.mode || 'BASE').toUpperCase();
				const list = data[mode] && data[mode].length ? data[mode] : data.BASE;
				// Walk the books in order rather than at random: a deterministic
				// sequence is what makes a bug reproducible.
				const book = list[state.spins % list.length];
				state.spins += 1;

				const amount = Number(body.amount) || M;
				const payout = Math.round(book.payoutMultiplier * amount);
				state.balance = state.balance - amount + payout;
				await saveState(state);

				lastRound = {
					betID: 900000 + state.spins,
					amount,
					payout,
					payoutMultiplier: book.payoutMultiplier,
					active: true,
					state: book.state,
					mode,
					event: null,
				};

				console.log('[play-mock]', mode, 'book', book.id, 'x' + book.payoutMultiplier);
				return json({ balance: { amount: state.balance, currency: 'USD' }, round: lastRound });
			}

			if (p.includes('/wallet/end-round')) {
				if (lastRound) lastRound.active = false;
				return json({ balance: { amount: state.balance, currency: 'USD' } });
			}

			// /bet/event — the client acks each event; nothing to return.
			return json({});
		})(),
	);
});
`;
fs.writeFileSync(path.join(OUT, 'play-mock-sw.js'), sw);

// The first load of a page is not controlled by a worker it registers itself, so
// the snippet reloads once as soon as the worker is active. Without that the
// app's very first authenticate would go to the real network.
const REGISTER = `		<script>
			(function () {
				if (!('serviceWorker' in navigator)) return;
				navigator.serviceWorker.register('./play-mock-sw.js').then(function (reg) {
					if (!navigator.serviceWorker.controller) {
						(reg.installing || reg.waiting || reg.active).addEventListener('statechange', function (e) {
							if (e.target.state === 'activated') location.reload();
						});
					}
				});
			})();
		</script>
`;
const indexPath = path.join(OUT, 'index.html');
const html = fs.readFileSync(indexPath, 'utf8');
fs.writeFileSync(indexPath, html.replace('</head>', REGISTER + '</head>'));

console.log(`[OK] play harness -> ${OUT}`);
console.log(`     books: ${counts}`);
console.log('     serve it, then open:');
console.log('       /?sessionID=playtest&rgs_url=mock.local&currency=USD&device=desktop&lang=en');
console.log('     replay mode (book 11 has free spins):');
console.log(
	'       /?replay=true&rgs_url=mock.local&currency=USD&device=desktop&lang=en' +
		'&game=wildparty&version=1&mode=BASE&event=11&amount=1000000',
);
