/**
 * GENERATED by design/build_parts_manifest.py — do not edit.
 *
 * Where each rigged part's ink actually sits, measured from the installed PNGs.
 * Canvas fractions with the origin at the centre of the cell: -0.5 is the left
 * or top edge, +0.5 the right or bottom — the same unit the motion tables use.
 *
 * `bbox` is [x0, y0, x1, y1] of the visible pixels; `centroid` is their mean
 * position, which is a better default pivot than the bbox centre for a part
 * whose mass sits off to one side.
 */
export type PartMetrics = {
	bbox: [number, number, number, number];
	centroid: [number, number];
	coverage: number;
};

export const PARTS_MANIFEST: Record<string, Record<string, PartMetrics>> = {
	"h1": {
		"arm": {
			"bbox": [
				0.1934,
				0.0781,
				0.459,
				0.4473
			],
			"centroid": [
				0.3097,
				0.2963
			],
			"coverage": 0.0762
		},
		"chain": {
			"bbox": [
				-0.1074,
				-0.1777,
				0.1074,
				0.0098
			],
			"centroid": [
				0.0002,
				-0.0747
			],
			"coverage": 0.0148
		},
		"head": {
			"bbox": [
				-0.1836,
				-0.4473,
				0.1855,
				-0.0391
			],
			"centroid": [
				0.0001,
				-0.2424
			],
			"coverage": 0.1193
		},
		"head_blink": {
			"bbox": [
				-0.1836,
				-0.4473,
				0.1855,
				-0.0391
			],
			"centroid": [
				0.0001,
				-0.2424
			],
			"coverage": 0.1193
		},
		"head_grin": {
			"bbox": [
				-0.1836,
				-0.4473,
				0.1855,
				-0.0391
			],
			"centroid": [
				0.0007,
				-0.2397
			],
			"coverage": 0.1214
		},
		"head_shades_down": {
			"bbox": [
				-0.1836,
				-0.4473,
				0.1855,
				-0.0391
			],
			"centroid": [
				0.0002,
				-0.2417
			],
			"coverage": 0.1198
		},
		"pose_peak": {
			"bbox": [
				-0.4551,
				-0.4434,
				0.4688,
				0.4707
			],
			"centroid": [
				-0.0111,
				0.1162
			],
			"coverage": 0.4678
		},
		"pose_settle": {
			"bbox": [
				-0.459,
				-0.4434,
				0.4629,
				0.4551
			],
			"centroid": [
				-0.0033,
				0.1183
			],
			"coverage": 0.4572
		},
		"pose_wind": {
			"bbox": [
				-0.4746,
				-0.4434,
				0.4512,
				0.4785
			],
			"centroid": [
				0.0091,
				0.1176
			],
			"coverage": 0.4616
		},
		"torso": {
			"bbox": [
				-0.4609,
				-0.0898,
				0.1934,
				0.4473
			],
			"centroid": [
				-0.0888,
				0.2198
			],
			"coverage": 0.2723
		}
	},
	"h2": {
		"hair_back": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"hair_front": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"head": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"head_blink": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"head_smile": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"head_wink": {
			"bbox": [
				-0.1738,
				-0.4023,
				0.2344,
				0.2227
			],
			"centroid": [
				0.028,
				-0.0607
			],
			"coverage": 0.2141
		},
		"pose_peak": {
			"bbox": [
				-0.1855,
				-0.377,
				0.2051,
				0.498
			],
			"centroid": [
				-0.0042,
				0.0996
			],
			"coverage": 0.2374
		},
		"pose_settle": {
			"bbox": [
				-0.1914,
				-0.3789,
				0.1992,
				0.4863
			],
			"centroid": [
				0.0056,
				0.0996
			],
			"coverage": 0.237
		},
		"pose_wind": {
			"bbox": [
				-0.2031,
				-0.373,
				0.1914,
				0.4961
			],
			"centroid": [
				0.0236,
				0.1017
			],
			"coverage": 0.2391
		},
		"torso": {
			"bbox": [
				-0.1973,
				-0.1289,
				0.1973,
				0.457
			],
			"centroid": [
				0.0101,
				0.1805
			],
			"coverage": 0.1949
		}
	},
	"h3": {
		"body": {
			"bbox": [
				-0.2363,
				-0.2168,
				0.2383,
				0.459
			],
			"centroid": [
				-0.0127,
				0.0136
			],
			"coverage": 0.1014
		},
		"head_neck": {
			"bbox": [
				-0.2402,
				-0.4609,
				-0.0312,
				-0.1641
			],
			"centroid": [
				-0.1295,
				-0.3386
			],
			"coverage": 0.0299
		},
		"head_neck_blink": {
			"bbox": [
				-0.2402,
				-0.4609,
				-0.0312,
				-0.1641
			],
			"centroid": [
				-0.1294,
				-0.3387
			],
			"coverage": 0.0295
		},
		"head_neck_squawk": {
			"bbox": [
				-0.2402,
				-0.4609,
				-0.0312,
				-0.1641
			],
			"centroid": [
				-0.1294,
				-0.3391
			],
			"coverage": 0.0308
		},
		"legs": {
			"bbox": [
				-0.1113,
				0.125,
				0.0938,
				0.459
			],
			"centroid": [
				-0.0225,
				0.29
			],
			"coverage": 0.0221
		},
		"pose_peak": {
			"bbox": [
				-0.3145,
				-0.4629,
				0.2383,
				0.4336
			],
			"centroid": [
				-0.0552,
				-0.0839
			],
			"coverage": 0.142
		},
		"pose_settle": {
			"bbox": [
				-0.2402,
				-0.4512,
				0.2383,
				0.4512
			],
			"centroid": [
				-0.0409,
				-0.0686
			],
			"coverage": 0.1332
		},
		"pose_wind": {
			"bbox": [
				-0.2402,
				-0.4297,
				0.2383,
				0.4609
			],
			"centroid": [
				-0.0409,
				-0.0512
			],
			"coverage": 0.1313
		},
		"wing": {
			"bbox": [
				-0.2363,
				-0.1289,
				0.0391,
				0.125
			],
			"centroid": [
				-0.0737,
				-0.0426
			],
			"coverage": 0.0424
		}
	},
	"h4": {
		"body": {
			"bbox": [
				-0.2324,
				-0.3262,
				0.2305,
				0.459
			],
			"centroid": [
				-0.0012,
				0.059
			],
			"coverage": 0.3562
		},
		"handle": {
			"bbox": [
				-0.2285,
				-0.4609,
				0.2305,
				-0.2949
			],
			"centroid": [
				0.0023,
				-0.3666
			],
			"coverage": 0.0462
		},
		"panel_lit": {
			"bbox": [
				-0.1602,
				-0.0234,
				0.1738,
				0.0566
			],
			"centroid": [
				-0.005,
				0.0137
			],
			"coverage": 0.0139
		},
		"pose_peak": {
			"bbox": [
				-0.2363,
				-0.4473,
				0.2344,
				0.459
			],
			"centroid": [
				-0.0019,
				0.0284
			],
			"coverage": 0.3847
		},
		"pose_settle": {
			"bbox": [
				-0.2324,
				-0.457,
				0.2305,
				0.459
			],
			"centroid": [
				-0.0013,
				0.0233
			],
			"coverage": 0.3844
		},
		"pose_wind": {
			"bbox": [
				-0.2305,
				-0.459,
				0.2285,
				0.459
			],
			"centroid": [
				-0.0013,
				0.0215
			],
			"coverage": 0.3842
		},
		"speaker_bottom": {
			"bbox": [
				-0.1348,
				0.0801,
				0.1328,
				0.3477
			],
			"centroid": [
				-0.002,
				0.2129
			],
			"coverage": 0.0553
		},
		"speaker_top": {
			"bbox": [
				-0.1348,
				-0.2695,
				0.1328,
				-0.002
			],
			"centroid": [
				-0.002,
				-0.1367
			],
			"coverage": 0.0553
		}
	},
	"h5": {
		"body": {
			"bbox": [
				-0.4609,
				-0.2129,
				0.459,
				0.2129
			],
			"centroid": [
				0.0012,
				-0.005
			],
			"coverage": 0.2524
		},
		"body_raw": {
			"bbox": [
				-0.4609,
				-0.2129,
				0.459,
				0.2129
			],
			"centroid": [
				0.0168,
				0.0009
			],
			"coverage": 0.267
		},
		"headlight": {
			"bbox": [
				0.3203,
				-0.0117,
				0.4375,
				0.0801
			],
			"centroid": [
				0.3736,
				0.0264
			],
			"coverage": 0.0077
		},
		"lights_on": {
			"bbox": [
				-0.334,
				0.0605,
				-0.1465,
				0.1172
			],
			"centroid": [
				-0.2507,
				0.0875
			],
			"coverage": 0.0034
		},
		"pose_peak": {
			"bbox": [
				-0.4902,
				-0.2227,
				0.4629,
				0.2012
			],
			"centroid": [
				-0.0019,
				-0.0142
			],
			"coverage": 0.2401
		},
		"pose_settle": {
			"bbox": [
				-0.4609,
				-0.2148,
				0.459,
				0.209
			],
			"centroid": [
				-0.0011,
				-0.0086
			],
			"coverage": 0.2388
		},
		"pose_wind": {
			"bbox": [
				-0.459,
				-0.2109,
				0.4551,
				0.2188
			],
			"centroid": [
				-0.0027,
				-0.0028
			],
			"coverage": 0.238
		},
		"wheel_front": {
			"bbox": [
				0.043,
				0.0176,
				0.166,
				0.1406
			],
			"centroid": [
				0.1055,
				0.0785
			],
			"coverage": 0.0114
		},
		"wheel_front_raw": {
			"bbox": [
				0.2324,
				-0.0215,
				0.4277,
				0.1738
			],
			"centroid": [
				0.3299,
				0.0773
			],
			"coverage": 0.0299
		},
		"wheel_rear": {
			"bbox": [
				0.3535,
				-0.0723,
				0.4453,
				0.0195
			],
			"centroid": [
				0.4025,
				-0.0278
			],
			"coverage": 0.0054
		},
		"wheel_rear_raw": {
			"bbox": [
				-0.3223,
				0.0508,
				-0.1758,
				0.1973
			],
			"centroid": [
				-0.2493,
				0.1227
			],
			"coverage": 0.0162
		}
	},
	"sw": {
		"core": {
			"bbox": [
				-0.3398,
				-0.3398,
				0.3418,
				0.3418
			],
			"centroid": [
				0.0,
				0.0
			],
			"coverage": 0.3669
		},
		"core_active": {
			"bbox": [
				-0.1484,
				-0.0176,
				0.1465,
				0.0645
			],
			"centroid": [
				0.0028,
				0.0277
			],
			"coverage": 0.0153
		},
		"pose_peak": {
			"bbox": [
				-0.4648,
				-0.4199,
				0.4648,
				0.4219
			],
			"centroid": [
				-0.001,
				-0.0009
			],
			"coverage": 0.5706
		},
		"pose_settle": {
			"bbox": [
				-0.4531,
				-0.4102,
				0.4531,
				0.4121
			],
			"centroid": [
				-0.001,
				-0.0009
			],
			"coverage": 0.5449
		},
		"pose_wind": {
			"bbox": [
				-0.4395,
				-0.3965,
				0.4395,
				0.4004
			],
			"centroid": [
				-0.0009,
				-0.0009
			],
			"coverage": 0.5117
		},
		"ring": {
			"bbox": [
				-0.459,
				-0.416,
				0.459,
				0.418
			],
			"centroid": [
				-0.0026,
				-0.0026
			],
			"coverage": 0.1926
		}
	}
};
