/**
 * GENERATED by design/build_parts_manifest.py — do not edit.
 *
 * Where each rigged part's ink actually sits, measured from the installed PNGs.
 * Canvas fractions with the origin at the centre of the cell: -0.5 is the left
 * or top edge, +0.5 the right or bottom — the same unit the motion tables use.
 *
 * `bbox` is [x0, y0, x1, y1] of the visible pixels; `centroid` is their mean
 * position, which is a better default pivot than the bbox centre for a part
 * whose mass sits off to one side.
 */
export type PartMetrics = {
	bbox: [number, number, number, number];
	centroid: [number, number];
	coverage: number;
};

export const PARTS_MANIFEST: Record<string, Record<string, PartMetrics>> = {
	"c": {
		"core": {
			"bbox": [
				-0.3398,
				-0.3398,
				0.3418,
				0.3418
			],
			"centroid": [
				0.0,
				0.0
			],
			"coverage": 0.3669
		},
		"ring": {
			"bbox": [
				-0.459,
				-0.416,
				0.459,
				0.418
			],
			"centroid": [
				-0.0026,
				-0.0026
			],
			"coverage": 0.1926
		}
	},
	"h1": {
		"arm": {
			"bbox": [
				0.1934,
				0.0781,
				0.459,
				0.4473
			],
			"centroid": [
				0.3097,
				0.2963
			],
			"coverage": 0.0762
		},
		"chain": {
			"bbox": [
				-0.1074,
				-0.1777,
				0.1074,
				0.0098
			],
			"centroid": [
				0.0002,
				-0.0747
			],
			"coverage": 0.0148
		},
		"head": {
			"bbox": [
				-0.1836,
				-0.4473,
				0.1855,
				-0.0391
			],
			"centroid": [
				0.0001,
				-0.2424
			],
			"coverage": 0.1193
		},
		"torso": {
			"bbox": [
				-0.4609,
				-0.0898,
				0.1934,
				0.4473
			],
			"centroid": [
				-0.0888,
				0.2198
			],
			"coverage": 0.2723
		}
	},
	"h2": {
		"hair_back": {
			"bbox": [
				-0.3691,
				-0.4375,
				0.3652,
				0.2051
			],
			"centroid": [
				0.0026,
				-0.0673
			],
			"coverage": 0.1768
		},
		"hair_front": {
			"bbox": [
				-0.3691,
				-0.207,
				0.3652,
				0.4453
			],
			"centroid": [
				-0.0015,
				0.0928
			],
			"coverage": 0.1784
		},
		"head": {
			"bbox": [
				-0.207,
				-0.3633,
				0.2051,
				0.0488
			],
			"centroid": [
				-0.0018,
				-0.148
			],
			"coverage": 0.1063
		},
		"torso": {
			"bbox": [
				-0.3809,
				0.0078,
				0.3809,
				0.459
			],
			"centroid": [
				-0.0008,
				0.2402
			],
			"coverage": 0.177
		}
	},
	"h3": {
		"body": {
			"bbox": [
				-0.2402,
				-0.4609,
				0.2383,
				0.459
			],
			"centroid": [
				-0.0571,
				-0.0432
			],
			"coverage": 0.108
		},
		"head_neck": {
			"bbox": [
				-0.0703,
				-0.4375,
				0.1914,
				-0.0684
			],
			"centroid": [
				0.0178,
				-0.1613
			],
			"coverage": 0.0298
		},
		"legs": {
			"bbox": [
				-0.1113,
				0.125,
				0.0938,
				0.459
			],
			"centroid": [
				-0.0225,
				0.29
			],
			"coverage": 0.0221
		},
		"wing": {
			"bbox": [
				-0.2363,
				-0.1289,
				0.0391,
				0.125
			],
			"centroid": [
				-0.0737,
				-0.0426
			],
			"coverage": 0.0424
		}
	},
	"h4": {
		"body": {
			"bbox": [
				-0.2324,
				-0.3262,
				0.2305,
				0.459
			],
			"centroid": [
				-0.0012,
				0.059
			],
			"coverage": 0.3562
		},
		"handle": {
			"bbox": [
				-0.2285,
				-0.4609,
				0.2305,
				-0.2949
			],
			"centroid": [
				0.0023,
				-0.3666
			],
			"coverage": 0.0462
		},
		"speaker_bottom": {
			"bbox": [
				-0.1348,
				0.0801,
				0.1328,
				0.3477
			],
			"centroid": [
				-0.002,
				0.2129
			],
			"coverage": 0.0553
		},
		"speaker_top": {
			"bbox": [
				-0.1348,
				-0.2695,
				0.1328,
				-0.002
			],
			"centroid": [
				-0.002,
				-0.1367
			],
			"coverage": 0.0553
		}
	}
};
