/**
 * GENERATED by design/build_parts_manifest.py — do not edit.
 *
 * Where each rigged part's ink actually sits, measured from the installed PNGs.
 * Canvas fractions with the origin at the centre of the cell: -0.5 is the left
 * or top edge, +0.5 the right or bottom — the same unit the motion tables use.
 *
 * `bbox` is [x0, y0, x1, y1] of the visible pixels; `centroid` is their mean
 * position, which is a better default pivot than the bbox centre for a part
 * whose mass sits off to one side.
 */
export type PartMetrics = {
	bbox: [number, number, number, number];
	centroid: [number, number];
	coverage: number;
};

export const PARTS_MANIFEST: Record<string, Record<string, PartMetrics>> = {
	"h4": {
		"body": {
			"bbox": [
				-0.2324,
				-0.3262,
				0.2305,
				0.459
			],
			"centroid": [
				-0.0012,
				0.059
			],
			"coverage": 0.3562
		},
		"handle": {
			"bbox": [
				-0.2285,
				-0.4609,
				0.2305,
				-0.2949
			],
			"centroid": [
				0.0023,
				-0.3666
			],
			"coverage": 0.0462
		},
		"speaker_bottom": {
			"bbox": [
				-0.1348,
				0.0801,
				0.1328,
				0.3477
			],
			"centroid": [
				-0.002,
				0.2129
			],
			"coverage": 0.0553
		},
		"speaker_top": {
			"bbox": [
				-0.1348,
				-0.2695,
				0.1328,
				-0.002
			],
			"centroid": [
				-0.002,
				-0.1367
			],
			"coverage": 0.0553
		}
	}
};
