#!/usr/bin/env python3
"""Measure the installed part PNGs and write src/game/partsManifest.ts.

A rigged part is a full-canvas image with its content in place, so the useful
facts about it — where its ink actually is, and therefore where a sensible pivot
lies — are in the pixels, not in anyone's head. Reading them here lets the motion
table say "the handle rotates about the bottom centre OF THE HANDLE" instead of
carrying hand-copied numbers that rot the moment the art is regenerated.

Everything is in CANVAS FRACTIONS with the origin at the centre of the cell:
-0.5 is the left/top edge, +0.5 the right/bottom. Same unit as the dx/dy in
symbolWinMotion.ts and symbolLandMotion.ts.

    python design/build_parts_manifest.py
"""
from __future__ import annotations
import json, os, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = os.path.join(ROOT, 'static/assets/sprites/hotMiamiParts')
OUT = os.path.join(ROOT, 'src/game/partsManifest.ts')


def measure(path: str):
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    alpha = im.getchannel('A')
    mask = alpha.point(lambda v: 255 if v > 32 else 0)
    box = mask.getbbox()
    if box is None:
        return None
    n = 0
    sx = sy = 0
    px = mask.load()
    for y in range(box[1], box[3]):
        for x in range(box[0], box[2]):
            if px[x, y]:
                sx += x
                sy += y
                n += 1
    f = lambda v, size: round(v / size - 0.5, 4)
    return {
        'bbox': [f(box[0], w), f(box[1], h), f(box[2], w), f(box[3], h)],
        'centroid': [f(sx / n, w), f(sy / n, h)],
        'coverage': round(n / (w * h), 4),
    }


def main() -> int:
    manifest: dict[str, dict] = {}
    for symbol in sorted(os.listdir(PARTS)) if os.path.isdir(PARTS) else []:
        d = os.path.join(PARTS, symbol)
        if not os.path.isdir(d):
            continue
        manifest[symbol] = {}
        for name in sorted(os.listdir(d)):
            if not name.endswith('.png') or name.startswith('_'):
                continue
            m = measure(os.path.join(d, name))
            if m is None:
                print(f'  !! {symbol}/{name} has no visible pixels')
                continue
            manifest[symbol][name[:-4]] = m
            print(f"   {symbol}/{name[:-4]:16s} bbox={m['bbox']} coverage={m['coverage']*100:.1f}%")

    body = '''/**
 * GENERATED by design/build_parts_manifest.py — do not edit.
 *
 * Where each rigged part's ink actually sits, measured from the installed PNGs.
 * Canvas fractions with the origin at the centre of the cell: -0.5 is the left
 * or top edge, +0.5 the right or bottom — the same unit the motion tables use.
 *
 * `bbox` is [x0, y0, x1, y1] of the visible pixels; `centroid` is their mean
 * position, which is a better default pivot than the bbox centre for a part
 * whose mass sits off to one side.
 */
export type PartMetrics = {
\tbbox: [number, number, number, number];
\tcentroid: [number, number];
\tcoverage: number;
};

export const PARTS_MANIFEST: Record<string, Record<string, PartMetrics>> = %s;
''' % json.dumps(manifest, indent='\t').replace('\n', '\n')
    with open(OUT, 'w') as f:
        f.write(body)
    print('wrote', os.path.relpath(OUT, ROOT))
    return 0


if __name__ == '__main__':
    sys.exit(main())
