export default {
	loader: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/loader/loader.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/loader/loader.json', import.meta.url).href,
			scale: 2,
		},
		preload: true,
	},
	// Drawn chrome icons for the bet-bar buttons, replacing the shared package's
	// text/emoji glyphs (see uiTheme.ts). Generated by design/build_neon_y2k_assets.py.
	wpIconMenu: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/menu.png', import.meta.url).href,
		preload: true,
	},
	wpIconMenuExit: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/menuExit.png', import.meta.url).href,
		preload: true,
	},
	wpIconSettings: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/settings.png', import.meta.url).href,
		preload: true,
	},
	wpIconInfo: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/info.png', import.meta.url).href,
		preload: true,
	},
	wpIconPayTable: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/payTable.png', import.meta.url).href,
		preload: true,
	},
	wpIconSoundOn: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/soundOn.png', import.meta.url).href,
		preload: true,
	},
	wpIconSoundOff: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/soundOff.png', import.meta.url).href,
		preload: true,
	},
	wpIconAutoSpin: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/autoSpin.png', import.meta.url).href,
		preload: true,
	},
	wpIconReplay: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyUiIcons/replay.png', import.meta.url).href,
		preload: true,
	},
	// Reel housing — three standalone sprites, not a sprite sheet.
	//
	// This was one 'sprites' atlas entry (reels_frame_v3.json) whose rects were
	// tied to a 3182x976 sheet layout. Swapping in new frame art of any other
	// size silently repointed every rect: the Neon Y2K frame is 2048x1536, so
	// frame_edge sampled a wrong crop and Frame_FSCounter's rect fell entirely
	// outside the image and drew nothing. Standalone files cannot fail that way —
	// and check_assets.mjs can see a missing file, where it could never have seen
	// a rect that no longer lands on artwork.
	frameEdge: {
		type: 'sprite',
		src: new URL('../../assets/sprites/reelsFrame/frame_edge.png', import.meta.url).href,
	},
	frameBg: {
		type: 'sprite',
		src: new URL('../../assets/sprites/reelsFrame/frame_bg.png', import.meta.url).href,
	},
	frameFsCounter: {
		type: 'sprite',
		src: new URL('../../assets/sprites/reelsFrame/frame_fs_counter.png', import.meta.url).href,
	},
	// soft corner-darkening overlay stretched over the whole canvas
	vignette: {
		type: 'sprite',
		src: new URL('../../assets/sprites/misc/vignette.png', import.meta.url).href,
		preload: true,
	},
	// Wild Party symbol art (transparent PNGs — swap files in
	// static/assets/sprites/wildPartySymbols/ to update the look)
	wpH1: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/h1.png', import.meta.url).href,
		preload: true,
	},
	wpH2: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/h2.png', import.meta.url).href,
		preload: true,
	},
	wpH3: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/h3.png', import.meta.url).href,
		preload: true,
	},
	wpH4: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/h4.png', import.meta.url).href,
		preload: true,
	},
	wpL1: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/l1.png', import.meta.url).href,
		preload: true,
	},
	wpL2: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/l2.png', import.meta.url).href,
		preload: true,
	},
	wpL3: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/l3.png', import.meta.url).href,
		preload: true,
	},
	wpL4: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/l4.png', import.meta.url).href,
		preload: true,
	},
	wpW: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/w.png', import.meta.url).href,
		preload: true,
	},
	wpS: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartySymbols/s.png', import.meta.url).href,
		preload: true,
	},
	wpSpH1: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/h1.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/h1.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpH2: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/h2.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/h2.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpH3: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/h3.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/h3.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpH4: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/h4.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/h4.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpL1: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/l1.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/l1.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpL2: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/l2.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/l2.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpL3: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/l3.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/l3.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpL4: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/l4.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/l4.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpW: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/w.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/w.json', import.meta.url).href,
			scale: 1,
		},
	},
	wpSpS: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/wildPartySymbols/s.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/wildPartySymbols/s.json', import.meta.url).href,
			scale: 1,
		},
	},
	// Wild Party themed backgrounds (placeholder art — swap files in
	// static/assets/sprites/wildPartyBackground/ to update the look)
	wildPartyBgBase: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyBackground/bg_base.png', import.meta.url).href,
		preload: true,
	},
	wildPartyBgFeature: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyBackground/bg_feature.png', import.meta.url).href,
		preload: true,
	},
	// soft-falloff FX textures (see design/generate_fx_textures.mjs)
	fxGlow: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyFx/fx_glow.png', import.meta.url).href,
		preload: true,
	},
	fxStar: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyFx/fx_star.png', import.meta.url).href,
		preload: true,
	},
	fxStreak: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyFx/fx_streak.png', import.meta.url).href,
		preload: true,
	},
	fxVignette: {
		type: 'sprite',
		src: new URL('../../assets/sprites/wildPartyFx/fx_vignette.png', import.meta.url).href,
		preload: true,
	},
	anticipation: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/anticipation/anticipation.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/anticipation/anticipation.json', import.meta.url).href,
			scale: 2,
		},
	},
	goldFont: {
		type: 'font',
		src: new URL('../../assets/fonts/goldFont/mm_gold.xml', import.meta.url).href,
	},
	goldBlur: {
		type: 'font',
		src: new URL('../../assets/fonts/goldBlur/miningfont_gold_blur.xml', import.meta.url).href,
	},
	silverFont: {
		type: 'font',
		src: new URL('../../assets/fonts/silverFont/mm_silver.xml', import.meta.url).href,
	},
	purpleFont: {
		type: 'font',
		src: new URL('../../assets/fonts/purpleFont/mm_purple.xml', import.meta.url).href,
	},
	// party-themed big win banners (SVG-generated — see design/generate_presentation.mjs)
	bigwin: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/bigwinParty/bigwin_party.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/bigwinParty/bigwin_party.json', import.meta.url).href,
			scale: 1,
		},
	},
	// AI-painted win-tier banner plaques (design/process_win_banners.mjs) —
	// the amount counts up inside each plaque's velvet center
	winBannerBig: {
		type: 'sprite',
		src: new URL('../../assets/sprites/winBanners/big.png', import.meta.url).href,
		preload: true,
	},
	winBannerSuperwin: {
		type: 'sprite',
		src: new URL('../../assets/sprites/winBanners/superwin.png', import.meta.url).href,
		preload: true,
	},
	winBannerMega: {
		type: 'sprite',
		src: new URL('../../assets/sprites/winBanners/mega.png', import.meta.url).href,
		preload: true,
	},
	winBannerEpic: {
		type: 'sprite',
		src: new URL('../../assets/sprites/winBanners/epic.png', import.meta.url).href,
		preload: true,
	},
	winBannerMax: {
		type: 'sprite',
		src: new URL('../../assets/sprites/winBanners/max.png', import.meta.url).href,
		preload: true,
	},
	// ornate FG intro/outro backdrop panel (generate_frames_v3.mjs 9-slice)
	fsOrnatePanel: {
		type: 'sprite',
		src: new URL('../../assets/sprites/fsOrnate/fs_ornate_panel.png', import.meta.url).href,
		preload: true,
	},
	globalMultiplier: {
		type: 'spine',
		src: {
			// v2 atlas/png: Frame_Multiplier repainted by generate_frames_v3.mjs
			atlas: new URL('../../assets/spines/globalMultiplier/multiframe_v2.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/globalMultiplier/multiframe.json', import.meta.url).href,
			scale: 2,
		},
	},
	tumble_multiplier: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/tumbleWin/tumble_win.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/tumbleWin/tumble_multiplier.json', import.meta.url).href,
			scale: 2,
		},
	},
	tumble_win: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/tumbleWin/tumble_win.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/tumbleWin/tumble_win.json', import.meta.url).href,
			scale: 2,
		},
	},
	reelhouse: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/reelhouse/reelhouse_glow.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/reelhouse/reelhouse_glow.json', import.meta.url).href,
			scale: 2,
		},
	},
	clusterWin: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/clusterWin/clusterpay.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/clusterWin/clusterpay.json', import.meta.url).href,
			scale: 2,
		},
	},
	transition: {
		type: 'spine',
		src: {
			atlas: new URL('../../assets/spines/transition/transition.atlas', import.meta.url).href,
			skeleton: new URL('../../assets/spines/transition/transition.json', import.meta.url).href,
			scale: 2,
		},
	},
	coins: {
		type: 'spriteSheet',
		src: new URL('../../assets/sprites/coin/SD2_Coin.json', import.meta.url).href,
	},
	sound: {
		type: 'audio',
		src: new URL('../../assets/audio/sounds.json', import.meta.url).href,
		preload: true,
	},
} as const;
