// Every asset path the game names must exist in the build output, with exactly
// the case it is written in.
//
// Two places name them, and both are checked here:
//
//   src/game/assets.ts     the pixi manifest, loaded through new URL(...)
//   src/game/betModeMeta   the bet-bar cards' icons, which are DOM <img> src
//                          strings built from `base` and never see the loader
//
// The second one was added after it failed. betModeMeta pointed all of its cards
// at buy_bags_1..3.png, generated by a script whose own source directory the game
// had deleted along with the mechanic those bags belonged to. Every card rendered
// with an empty box where the icon goes, for as long as it took someone to look:
// an <img> with a 404 src throws nothing, logs nothing outside the network tab,
// and lays out at zero size. The pixi loader at least stalls loudly.
//
// A missing one 404s at load time and — because the preloader waits on the whole
// batch — can leave the game stuck on the loading screen.
//
// The case check matters as much as the existence check on this project: we
// develop on Windows, where the filesystem is case-insensitive, and ship to a
// server where it is not. `w.png` referenced against a `W.png` on disk resolves
// perfectly here and 404s in production, and every other guard we have would
// stay green. That has already happened once.
//
// Usage: node design/check_assets.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = fs.readFileSync(path.join(appRoot, 'src/game/assets.ts'), 'utf8');
const staticRoot = path.join(appRoot, 'static');

let problems = 0;
let checked = 0;

const dirCache = new Map();
const entriesOf = (dir) => {
	if (!dirCache.has(dir)) {
		dirCache.set(dir, fs.existsSync(dir) ? fs.readdirSync(dir) : []);
	}
	return dirCache.get(dir);
};

/** Walk a relative path segment by segment, comparing each against the real
 *  directory listing. That is the only way to see a case difference on a
 *  case-insensitive filesystem — fs.existsSync cannot. */
const check = (label, rel) => {
	checked++;
	const full = path.join(staticRoot, rel);
	if (!fs.existsSync(full)) {
		console.log(`  !! missing: ${label}  →  static/${rel}`);
		problems++;
		return;
	}
	let dir = staticRoot;
	for (const segment of rel.split('/')) {
		const entries = entriesOf(dir);
		if (!entries.includes(segment)) {
			const actual = entries.find((e) => e.toLowerCase() === segment.toLowerCase());
			console.log(
				`  !! case mismatch: ${label}  →  wants "${segment}", on disk "${actual}"` +
					' (resolves on Windows, 404s on the server)',
			);
			problems++;
			return;
		}
		dir = path.join(dir, segment);
	}
};

// new URL('../../assets/…', import.meta.url) is resolved at RUNTIME against the
// served bundle URL (_app/immutable/…), so it lands on /assets/… — i.e. static/.
// It is not a build-time import, which is exactly why a typo here fails as a
// silent 404 instead of breaking the build.
for (const m of source.matchAll(/new URL\(\s*['"`]([^'"`]+)['"`]\s*,\s*import\.meta\.url/g)) {
	check(m[1], m[1].replace(/^(?:\.\.\/)+/, ''));
}

for (const m of source.matchAll(/src:\s*['"`](\/[^'"`\s]+)['"`]/g)) {
	check(m[1], m[1].replace(/^\//, ''));
}

// DOM <img> srcs, written as `${base}/assets/…` template literals. `base` is
// SvelteKit's deployment path prefix and is empty in this app's config, so the
// path after it is a static/ path. Matched on the literal rather than evaluated,
// because evaluating the module would mean booting SvelteKit.
const domSources = fs.readFileSync(path.join(appRoot, 'src/game/betModeMeta.ts'), 'utf8');
for (const m of domSources.matchAll(/\$\{base\}(\/assets\/[^'"`\s]+)/g)) {
	// Icons are named per mode through a lookup, so the literal carries a
	// `${copy.art}` hole. Expand it against the values the table actually holds -
	// a check that only verified the directory would have passed the bags bug.
	const literal = m[1];
	const hole = literal.match(/\$\{[^}]+\}/);
	if (!hole) {
		check(literal, literal.replace(/^\//, ''));
		continue;
	}
	const values = [...domSources.matchAll(/^\t\tart: '([^']+)',$/gm)].map((v) => v[1]);
	if (values.length === 0) {
		console.log(`  !! ${literal} is templated but no art: values were found to expand it with`);
		problems++;
		continue;
	}
	for (const value of values) {
		const rel = literal.replace(hole[0], value);
		check(rel, rel.replace(/^\//, ''));
	}
}

console.log(
	problems === 0
		? `OK: all ${checked} asset paths resolve`
		: `${problems} of ${checked} asset path(s) wrong`,
);
process.exit(problems === 0 ? 0 : 1);
