// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "L2"
    },
    {
     "name": "L1"
    },
    {
     "name": "H2"
    },
    {
     "name": "L4"
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "L2"
    },
    {
     "name": "H5"
    },
    {
     "name": "H4"
    },
    {
     "name": "L1"
    },
    {
     "name": "H4"
    },
    {
     "name": "H5"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "L1"
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "H5"
    },
    {
     "name": "H2"
    },
    {
     "name": "H4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L2"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "L3"
    },
    {
     "name": "H2"
    },
    {
     "name": "L4"
    },
    {
     "name": "H5"
    },
    {
     "name": "L2"
    }
   ]
  ],
  "paddingPositions": [
   61,
   27,
   8,
   14,
   25
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   0,
   0
  ]
 },
 "winInfo": {
  "index": 1,
  "type": "winInfo",
  "totalWin": 20,
  "wins": [
   {
    "symbol": "L1",
    "kind": 3,
    "win": 20,
    "positions": [
     {
      "reel": 0,
      "row": 4
     },
     {
      "reel": 1,
      "row": 3
     },
     {
      "reel": 2,
      "row": 4
     }
    ],
    "meta": {
     "lineIndex": 14,
     "multiplier": 1,
     "winWithoutMult": 20,
     "globalMult": 1,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 2,
  "type": "setWin",
  "amount": 20,
  "winLevel": 2
 },
 "setTotalWin": {
  "index": 3,
  "type": "setTotalWin",
  "amount": 20
 },
 "finalWin": {
  "index": 4,
  "type": "finalWin",
  "amount": 20
 },
 "freeSpinTrigger": {
  "index": 4,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 0,
    "row": 1
   },
   {
    "reel": 1,
    "row": 4
   },
   {
    "reel": 3,
    "row": 4
   }
  ]
 },
 "bonusTier": {
  "index": 5,
  "type": "bonusTier",
  "tier": "midnight_passage",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 6,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 8,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 8,
  "eligibleValues": [
   2,
   4,
   6,
   8,
   10,
   12,
   16,
   20,
   30,
   40,
   50,
   60,
   80,
   100,
   150,
   200
  ]
 },
 "freeSpinEnd": {
  "index": 51,
  "type": "freeSpinEnd",
  "amount": 25280,
  "winLevel": 7
 },
 "freeSpinRetrigger": {
  "index": 19,
  "type": "freeSpinRetrigger",
  "totalFs": 12,
  "positions": [
   {
    "reel": 2,
    "row": 4
   },
   {
    "reel": 4,
    "row": 4
   }
  ]
 }
};
