// Generated by design/sync_story_books.py from books_base.jsonl.zst — do not edit by hand.
export default [
 {
  "id": 31242,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     61,
     27,
     8,
     14,
     25
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 14,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 },
 {
  "id": 13481,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      }
     ]
    ],
    "paddingPositions": [
     5,
     10,
     21,
     57,
     28
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 8,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 },
 {
  "id": 19564,
  "payoutMultiplier": 50,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ]
    ],
    "paddingPositions": [
     20,
     58,
     48,
     40,
     17
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 50,
    "wins": [
     {
      "symbol": "L1",
      "kind": 4,
      "win": 50,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 4
       },
       {
        "reel": 2,
        "row": 4
       },
       {
        "reel": 3,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 4,
       "multiplier": 1,
       "winWithoutMult": 50,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 50,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 50
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 50
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.5,
  "freeGameWins": 0.0
 },
 {
  "id": 5498,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     58,
     3,
     2,
     24,
     42
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 7,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 },
 {
  "id": 25575,
  "payoutMultiplier": 25300,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      }
     ]
    ],
    "paddingPositions": [
     48,
     6,
     4,
     24,
     10
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     1,
     2,
     3
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 11,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "freeSpinTrigger",
    "totalFs": 10,
    "positions": [
     {
      "reel": 0,
      "row": 1
     },
     {
      "reel": 1,
      "row": 4
     },
     {
      "reel": 3,
      "row": 4
     }
    ]
   },
   {
    "index": 5,
    "type": "bonusTier",
    "tier": "midnight_passage",
    "seedFrames": 0
   },
   {
    "index": 6,
    "type": "updateFreeSpin",
    "amount": 0,
    "total": 10
   },
   {
    "index": 7,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     57,
     40,
     6,
     26,
     1
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 8,
    "type": "multiplierWheel",
    "previous": 1,
    "value": 8,
    "eligibleValues": [
     2,
     4,
     6,
     8,
     10,
     12,
     16,
     20,
     30,
     40,
     50,
     60,
     80,
     100,
     150,
     200
    ]
   },
   {
    "index": 9,
    "type": "winInfo",
    "totalWin": 160,
    "wins": [
     {
      "symbol": "L3",
      "kind": 3,
      "win": 160,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 8,
       "multiplier": 8,
       "winWithoutMult": 20,
       "globalMult": 8,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 10,
    "type": "setWin",
    "amount": 160,
    "winLevel": 3
   },
   {
    "index": 11,
    "type": "setTotalWin",
    "amount": 180
   },
   {
    "index": 12,
    "type": "updateFreeSpin",
    "amount": 1,
    "total": 10
   },
   {
    "index": 13,
    "type": "reveal",
    "board": [
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     6,
     42,
     32,
     2,
     50
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 14,
    "type": "multiplierWheel",
    "previous": 8,
    "value": 8,
    "eligibleValues": [
     8,
     10,
     12,
     16,
     20,
     30,
     40,
     50,
     60,
     80,
     100,
     150,
     200
    ]
   },
   {
    "index": 15,
    "type": "winInfo",
    "totalWin": 20000,
    "wins": [
     {
      "symbol": "H3",
      "kind": 5,
      "win": 20000,
      "positions": [
       {
        "reel": 0,
        "row": 3
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       },
       {
        "reel": 3,
        "row": 2
       },
       {
        "reel": 4,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 11,
       "multiplier": 8,
       "winWithoutMult": 2500,
       "globalMult": 8,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 16,
    "type": "setWin",
    "amount": 20000,
    "winLevel": 9
   },
   {
    "index": 17,
    "type": "setTotalWin",
    "amount": 20180
   },
   {
    "index": 18,
    "type": "updateFreeSpin",
    "amount": 2,
    "total": 10
   },
   {
    "index": 19,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ]
    ],
    "paddingPositions": [
     4,
     19,
     27,
     0,
     28
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 20,
    "type": "multiplierWheel",
    "previous": 8,
    "value": 8,
    "eligibleValues": [
     8,
     10,
     12,
     16,
     20,
     30,
     40,
     50,
     60,
     80,
     100,
     150,
     200
    ]
   },
   {
    "index": 21,
    "type": "winInfo",
    "totalWin": 160,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 160,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 10,
       "multiplier": 8,
       "winWithoutMult": 20,
       "globalMult": 8,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 22,
    "type": "setWin",
    "amount": 160,
    "winLevel": 3
   },
   {
    "index": 23,
    "type": "setTotalWin",
    "amount": 20340
   },
   {
    "index": 24,
    "type": "updateFreeSpin",
    "amount": 3,
    "total": 10
   },
   {
    "index": 25,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      }
     ]
    ],
    "paddingPositions": [
     48,
     21,
     13,
     24,
     45
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 26,
    "type": "setTotalWin",
    "amount": 20340
   },
   {
    "index": 27,
    "type": "updateFreeSpin",
    "amount": 4,
    "total": 10
   },
   {
    "index": 28,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ]
    ],
    "paddingPositions": [
     23,
     2,
     15,
     14,
     42
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 29,
    "type": "setTotalWin",
    "amount": 20340
   },
   {
    "index": 30,
    "type": "updateFreeSpin",
    "amount": 5,
    "total": 10
   },
   {
    "index": 31,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "H1"
      }
     ]
    ],
    "paddingPositions": [
     15,
     3,
     46,
     49,
     43
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 32,
    "type": "multiplierWheel",
    "previous": 8,
    "value": 8,
    "eligibleValues": [
     8,
     10,
     12,
     16,
     20,
     30,
     40,
     50,
     60,
     80,
     100,
     150,
     200
    ]
   },
   {
    "index": 33,
    "type": "winInfo",
    "totalWin": 160,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 160,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 5,
       "multiplier": 8,
       "winWithoutMult": 20,
       "globalMult": 8,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 34,
    "type": "setWin",
    "amount": 160,
    "winLevel": 3
   },
   {
    "index": 35,
    "type": "setTotalWin",
    "amount": 20500
   },
   {
    "index": 36,
    "type": "updateFreeSpin",
    "amount": 6,
    "total": 10
   },
   {
    "index": 37,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      }
     ]
    ],
    "paddingPositions": [
     57,
     4,
     36,
     34,
     37
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 38,
    "type": "setTotalWin",
    "amount": 20500
   },
   {
    "index": 39,
    "type": "updateFreeSpin",
    "amount": 7,
    "total": 10
   },
   {
    "index": 40,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      }
     ]
    ],
    "paddingPositions": [
     5,
     52,
     41,
     56,
     11
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 41,
    "type": "setTotalWin",
    "amount": 20500
   },
   {
    "index": 42,
    "type": "updateFreeSpin",
    "amount": 8,
    "total": 10
   },
   {
    "index": 43,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     13,
     20,
     42,
     43,
     25
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     1
    ]
   },
   {
    "index": 44,
    "type": "multiplierWheel",
    "previous": 8,
    "value": 16,
    "eligibleValues": [
     8,
     10,
     12,
     16,
     20,
     30,
     40,
     50,
     60,
     80,
     100,
     150,
     200
    ]
   },
   {
    "index": 45,
    "type": "winInfo",
    "totalWin": 4800,
    "wins": [
     {
      "symbol": "H4",
      "kind": 3,
      "win": 1600,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 4
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 4,
       "multiplier": 16,
       "winWithoutMult": 100,
       "globalMult": 16,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "H3",
      "kind": 3,
      "win": 3200,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 6,
       "multiplier": 16,
       "winWithoutMult": 200,
       "globalMult": 16,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 46,
    "type": "setWin",
    "amount": 4800,
    "winLevel": 7
   },
   {
    "index": 47,
    "type": "setTotalWin",
    "amount": 25300
   },
   {
    "index": 48,
    "type": "updateFreeSpin",
    "amount": 9,
    "total": 10
   },
   {
    "index": 49,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      }
     ]
    ],
    "paddingPositions": [
     28,
     19,
     60,
     59,
     34
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 50,
    "type": "setTotalWin",
    "amount": 25300
   },
   {
    "index": 51,
    "type": "freeSpinEnd",
    "amount": 25280,
    "winLevel": 7
   },
   {
    "index": 52,
    "type": "finalWin",
    "amount": 25300
   }
  ],
  "criteria": "freegame_weak",
  "baseGameWins": 0.2,
  "freeGameWins": 252.8
 },
 {
  "id": 20653,
  "payoutMultiplier": 70,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     16,
     1,
     4,
     1,
     5
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 70,
    "wins": [
     {
      "symbol": "L3",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 5,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "H5",
      "kind": 3,
      "win": 50,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 7,
       "multiplier": 1,
       "winWithoutMult": 50,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 70,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 70
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 70
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.7,
  "freeGameWins": 0.0
 },
 {
  "id": 27236,
  "payoutMultiplier": 40,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      }
     ]
    ],
    "paddingPositions": [
     41,
     36,
     39,
     19,
     3
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 40,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 7,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "L1",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 14,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 40,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 40
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 40
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.4,
  "freeGameWins": 0.0
 },
 {
  "id": 8781,
  "payoutMultiplier": 200,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     47,
     38,
     51,
     10,
     25
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 200,
    "wins": [
     {
      "symbol": "H3",
      "kind": 3,
      "win": 200,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 10,
       "multiplier": 1,
       "winWithoutMult": 200,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 200,
    "winLevel": 4
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 200
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 200
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 2.0,
  "freeGameWins": 0.0
 },
 {
  "id": 2970,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "S",
       "scatter": true
      }
     ]
    ],
    "paddingPositions": [
     24,
     16,
     53,
     9,
     63
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 1
       },
       {
        "reel": 1,
        "row": 1
       },
       {
        "reel": 2,
        "row": 1
       }
      ],
      "meta": {
       "lineIndex": 1,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 },
 {
  "id": 26285,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     4,
     37,
     35,
     50,
     53
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L2",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 12,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 },
 {
  "id": 16549,
  "payoutMultiplier": 7900,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      }
     ]
    ],
    "paddingPositions": [
     61,
     47,
     17,
     24,
     36
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     1,
     2,
     3
    ]
   },
   {
    "index": 1,
    "type": "setTotalWin",
    "amount": 0
   },
   {
    "index": 2,
    "type": "freeSpinTrigger",
    "totalFs": 10,
    "positions": [
     {
      "reel": 0,
      "row": 3
     },
     {
      "reel": 1,
      "row": 4
     },
     {
      "reel": 2,
      "row": 1
     },
     {
      "reel": 3,
      "row": 4
     },
     {
      "reel": 4,
      "row": 2
     }
    ]
   },
   {
    "index": 3,
    "type": "bonusTier",
    "tier": "phantom_express",
    "seedFrames": 0
   },
   {
    "index": 4,
    "type": "updateFreeSpin",
    "amount": 0,
    "total": 10
   },
   {
    "index": 5,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H1"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     58,
     21,
     20,
     2,
     17
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 6,
    "type": "multiplierWheel",
    "previous": 1,
    "value": 10,
    "eligibleValues": [
     10,
     20,
     30,
     40,
     50,
     60,
     70,
     80,
     90,
     100,
     110,
     120,
     130,
     140,
     150,
     160,
     170,
     180,
     190,
     200
    ]
   },
   {
    "index": 7,
    "type": "winInfo",
    "totalWin": 500,
    "wins": [
     {
      "symbol": "H5",
      "kind": 3,
      "win": 500,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 4
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 4,
       "multiplier": 10,
       "winWithoutMult": 50,
       "globalMult": 10,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 8,
    "type": "setWin",
    "amount": 500,
    "winLevel": 5
   },
   {
    "index": 9,
    "type": "setTotalWin",
    "amount": 500
   },
   {
    "index": 10,
    "type": "updateFreeSpin",
    "amount": 1,
    "total": 10
   },
   {
    "index": 11,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     14,
     51,
     52,
     20,
     50
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 12,
    "type": "multiplierWheel",
    "previous": 10,
    "value": 10,
    "eligibleValues": [
     10,
     20,
     30,
     40,
     50,
     60,
     70,
     80,
     90,
     100,
     110,
     120,
     130,
     140,
     150,
     160,
     170,
     180,
     190,
     200
    ]
   },
   {
    "index": 13,
    "type": "winInfo",
    "totalWin": 400,
    "wins": [
     {
      "symbol": "L4",
      "kind": 3,
      "win": 200,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 6,
       "multiplier": 10,
       "winWithoutMult": 20,
       "globalMult": 10,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "L4",
      "kind": 3,
      "win": 200,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 14,
       "multiplier": 10,
       "winWithoutMult": 20,
       "globalMult": 10,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 14,
    "type": "setWin",
    "amount": 400,
    "winLevel": 4
   },
   {
    "index": 15,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 16,
    "type": "updateFreeSpin",
    "amount": 2,
    "total": 10
   },
   {
    "index": 17,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L2"
      }
     ]
    ],
    "paddingPositions": [
     9,
     44,
     2,
     45,
     54
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     1,
     2
    ]
   },
   {
    "index": 18,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 19,
    "type": "freeSpinRetrigger",
    "totalFs": 12,
    "positions": [
     {
      "reel": 2,
      "row": 4
     },
     {
      "reel": 4,
      "row": 4
     }
    ]
   },
   {
    "index": 20,
    "type": "updateFreeSpin",
    "amount": 3,
    "total": 12
   },
   {
    "index": 21,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      }
     ]
    ],
    "paddingPositions": [
     8,
     24,
     47,
     35,
     32
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 22,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 23,
    "type": "updateFreeSpin",
    "amount": 4,
    "total": 12
   },
   {
    "index": 24,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H2"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      }
     ]
    ],
    "paddingPositions": [
     46,
     45,
     9,
     44,
     40
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     1
    ]
   },
   {
    "index": 25,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 26,
    "type": "updateFreeSpin",
    "amount": 5,
    "total": 12
   },
   {
    "index": 27,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      }
     ]
    ],
    "paddingPositions": [
     35,
     57,
     61,
     63,
     40
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 28,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 29,
    "type": "updateFreeSpin",
    "amount": 6,
    "total": 12
   },
   {
    "index": 30,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "S",
       "scatter": true
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H1"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      }
     ]
    ],
    "paddingPositions": [
     59,
     32,
     33,
     5,
     20
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 31,
    "type": "setTotalWin",
    "amount": 900
   },
   {
    "index": 32,
    "type": "updateFreeSpin",
    "amount": 7,
    "total": 12
   },
   {
    "index": 33,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     37,
     22,
     23,
     38,
     61
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 34,
    "type": "multiplierWheel",
    "previous": 10,
    "value": 20,
    "eligibleValues": [
     10,
     20,
     30,
     40,
     50,
     60,
     70,
     80,
     90,
     100,
     110,
     120,
     130,
     140,
     150,
     160,
     170,
     180,
     190,
     200
    ]
   },
   {
    "index": 35,
    "type": "winInfo",
    "totalWin": 7000,
    "wins": [
     {
      "symbol": "L3",
      "kind": 4,
      "win": 1000,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 2
       },
       {
        "reel": 3,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 7,
       "multiplier": 20,
       "winWithoutMult": 50,
       "globalMult": 20,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "H3",
      "kind": 3,
      "win": 4000,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 3
       }
      ],
      "meta": {
       "lineIndex": 12,
       "multiplier": 20,
       "winWithoutMult": 200,
       "globalMult": 20,
       "lineMultiplier": 1
      }
     },
     {
      "symbol": "H4",
      "kind": 3,
      "win": 2000,
      "positions": [
       {
        "reel": 0,
        "row": 4
       },
       {
        "reel": 1,
        "row": 3
       },
       {
        "reel": 2,
        "row": 4
       }
      ],
      "meta": {
       "lineIndex": 14,
       "multiplier": 20,
       "winWithoutMult": 100,
       "globalMult": 20,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 36,
    "type": "setWin",
    "amount": 7000,
    "winLevel": 8
   },
   {
    "index": 37,
    "type": "setTotalWin",
    "amount": 7900
   },
   {
    "index": 38,
    "type": "updateFreeSpin",
    "amount": 8,
    "total": 12
   },
   {
    "index": 39,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      }
     ]
    ],
    "paddingPositions": [
     21,
     52,
     61,
     38,
     48
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 40,
    "type": "setTotalWin",
    "amount": 7900
   },
   {
    "index": 41,
    "type": "updateFreeSpin",
    "amount": 9,
    "total": 12
   },
   {
    "index": 42,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      }
     ],
     [
      {
       "name": "H1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      }
     ]
    ],
    "paddingPositions": [
     17,
     60,
     12,
     59,
     11
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 43,
    "type": "setTotalWin",
    "amount": 7900
   },
   {
    "index": 44,
    "type": "updateFreeSpin",
    "amount": 10,
    "total": 12
   },
   {
    "index": 45,
    "type": "reveal",
    "board": [
     [
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H5"
      },
      {
       "name": "H3"
      },
      {
       "name": "L4"
      }
     ],
     [
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L2"
      },
      {
       "name": "H3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "H5"
      },
      {
       "name": "H1"
      },
      {
       "name": "L2"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     14,
     22,
     34,
     17,
     46
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 46,
    "type": "setTotalWin",
    "amount": 7900
   },
   {
    "index": 47,
    "type": "updateFreeSpin",
    "amount": 11,
    "total": 12
   },
   {
    "index": 48,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L2"
      },
      {
       "name": "H1"
      },
      {
       "name": "H3"
      },
      {
       "name": "H1"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H2"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "L3"
      },
      {
       "name": "L1"
      },
      {
       "name": "L4"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      }
     ]
    ],
    "paddingPositions": [
     22,
     1,
     48,
     61,
     50
    ],
    "gameType": "freegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 49,
    "type": "setTotalWin",
    "amount": 7900
   },
   {
    "index": 50,
    "type": "freeSpinEnd",
    "amount": 7900,
    "winLevel": 6
   },
   {
    "index": 51,
    "type": "finalWin",
    "amount": 7900
   }
  ],
  "criteria": "freegame_strong",
  "baseGameWins": 0.0,
  "freeGameWins": 79.0
 },
 {
  "id": 5939,
  "payoutMultiplier": 20,
  "events": [
   {
    "index": 0,
    "type": "reveal",
    "board": [
     [
      {
       "name": "H2"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "H2"
      },
      {
       "name": "L2"
      }
     ],
     [
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "L1"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      }
     ],
     [
      {
       "name": "L2"
      },
      {
       "name": "H2"
      },
      {
       "name": "W",
       "wild": true
      },
      {
       "name": "L4"
      },
      {
       "name": "L3"
      },
      {
       "name": "H4"
      }
     ],
     [
      {
       "name": "H4"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      },
      {
       "name": "H5"
      },
      {
       "name": "L4"
      },
      {
       "name": "H3"
      }
     ],
     [
      {
       "name": "H3"
      },
      {
       "name": "L3"
      },
      {
       "name": "L4"
      },
      {
       "name": "H5"
      },
      {
       "name": "L1"
      },
      {
       "name": "S",
       "scatter": true
      }
     ]
    ],
    "paddingPositions": [
     63,
     44,
     22,
     50,
     33
    ],
    "gameType": "basegame",
    "anticipation": [
     0,
     0,
     0,
     0,
     0
    ]
   },
   {
    "index": 1,
    "type": "winInfo",
    "totalWin": 20,
    "wins": [
     {
      "symbol": "L1",
      "kind": 3,
      "win": 20,
      "positions": [
       {
        "reel": 0,
        "row": 2
       },
       {
        "reel": 1,
        "row": 2
       },
       {
        "reel": 2,
        "row": 2
       }
      ],
      "meta": {
       "lineIndex": 2,
       "multiplier": 1,
       "winWithoutMult": 20,
       "globalMult": 1,
       "lineMultiplier": 1
      }
     }
    ]
   },
   {
    "index": 2,
    "type": "setWin",
    "amount": 20,
    "winLevel": 2
   },
   {
    "index": 3,
    "type": "setTotalWin",
    "amount": 20
   },
   {
    "index": 4,
    "type": "finalWin",
    "amount": 20
   }
  ],
  "criteria": "basegame",
  "baseGameWins": 0.2,
  "freeGameWins": 0.0
 }
];
