// Generated by design/sync_story_books.py from books_bonus_hits.jsonl.zst — do not edit by hand.
export default {
 "reveal": {
  "index": 0,
  "type": "reveal",
  "board": [
   [
    {
     "name": "H5"
    },
    {
     "name": "L4"
    },
    {
     "name": "H2"
    },
    {
     "name": "H5"
    },
    {
     "name": "L3"
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "H4"
    },
    {
     "name": "L3"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    },
    {
     "name": "H4"
    }
   ],
   [
    {
     "name": "L2"
    },
    {
     "name": "L3"
    },
    {
     "name": "L2"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L3"
    }
   ],
   [
    {
     "name": "H1"
    },
    {
     "name": "H2"
    },
    {
     "name": "H3"
    },
    {
     "name": "H2"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "L1"
    }
   ],
   [
    {
     "name": "L3"
    },
    {
     "name": "H5"
    },
    {
     "name": "S",
     "scatter": true
    },
    {
     "name": "H3"
    },
    {
     "name": "L4"
    },
    {
     "name": "L2"
    }
   ]
  ],
  "paddingPositions": [
   28,
   15,
   6,
   24,
   17
  ],
  "gameType": "basegame",
  "anticipation": [
   0,
   0,
   0,
   1,
   2
  ]
 },
 "setTotalWin": {
  "index": 1,
  "type": "setTotalWin",
  "amount": 0
 },
 "freeSpinTrigger": {
  "index": 2,
  "type": "freeSpinTrigger",
  "totalFs": 10,
  "positions": [
   {
    "reel": 1,
    "row": 2
   },
   {
    "reel": 2,
    "row": 4
   },
   {
    "reel": 3,
    "row": 4
   },
   {
    "reel": 4,
    "row": 2
   }
  ]
 },
 "bonusTier": {
  "index": 3,
  "type": "bonusTier",
  "tier": "phantom_express",
  "seedFrames": 0
 },
 "updateFreeSpin": {
  "index": 4,
  "type": "updateFreeSpin",
  "amount": 0,
  "total": 10
 },
 "multiplierWheel": {
  "index": 12,
  "type": "multiplierWheel",
  "previous": 1,
  "value": 10,
  "eligibleValues": [
   10,
   20,
   30,
   40,
   50,
   60,
   70,
   80,
   90,
   100,
   110,
   120,
   130,
   140,
   150,
   160,
   170,
   180,
   190,
   200
  ]
 },
 "winInfo": {
  "index": 13,
  "type": "winInfo",
  "totalWin": 2000,
  "wins": [
   {
    "symbol": "H3",
    "kind": 3,
    "win": 2000,
    "positions": [
     {
      "reel": 0,
      "row": 1
     },
     {
      "reel": 1,
      "row": 2
     },
     {
      "reel": 2,
      "row": 2
     }
    ],
    "meta": {
     "lineIndex": 9,
     "multiplier": 10,
     "winWithoutMult": 200,
     "globalMult": 10,
     "lineMultiplier": 1
    }
   }
  ]
 },
 "setWin": {
  "index": 14,
  "type": "setWin",
  "amount": 2000,
  "winLevel": 6
 },
 "freeSpinEnd": {
  "index": 46,
  "type": "freeSpinEnd",
  "amount": 13400,
  "winLevel": 7
 },
 "finalWin": {
  "index": 47,
  "type": "finalWin",
  "amount": 13400
 },
 "freeSpinRetrigger": {
  "index": 28,
  "type": "freeSpinRetrigger",
  "totalFs": 14,
  "positions": [
   {
    "reel": 0,
    "row": 3
   },
   {
    "reel": 2,
    "row": 2
   },
   {
    "reel": 3,
    "row": 3
   }
  ]
 }
};
